docs/modules/ROOT/partials/component-attributes.adoc, docs/modules/pkl-cli/pages/index.adoc
=> Fix download instructions

docs/modules/ROOT/partials/component-attributes.adoc
(cherry picked from commit 3f8fae48733490b97dab80e47fb2a116fde4d753)
=> fix wrong stdlib doc links (#74)

pkl-core/src/main/java/org/pkl/core/runtime/VmExceptionRenderer.java
Crash help text has mangled URL #61
=> fix mangled url

pkl-cli/pkl-cli.gradle.kts
=> remove duplicate publishing of pkl-cli-java

docs/modules/ROOT/partials/component-attributes.adoc, docs/modules/java-binding/pages/pkl-config-java.adoc, docs/modules/kotlin-binding/pages/pkl-config-kotlin.adoc, docs/modules/language-reference/pages/index.adoc, docs/modules/pkl-core/pages/index.adoc
This fixes the rest of the links that are producing 404's.
=> Fix more links

pkl-core/src/main/java/org/pkl/core/util/MathUtils.java
minor fix in the mathUtils.java file
=> logical and fix in mathUtils

docs/modules/java-binding/pages/codegen.adoc, docs/modules/java-binding/pages/pkl-config-java.adoc, docs/modules/kotlin-binding/pages/codegen.adoc, docs/modules/kotlin-binding/pages/pkl-config-kotlin.adoc, docs/modules/pkl-core/pages/index.adoc, docs/modules/pkl-doc/pages/index.adoc, docs/modules/pkl-gradle/pages/index.adoc
* Use `mavenCentral()` if release version
* Use `sonatype` if snapshot version
=> Fix docs pointing to wrong maven repo

DEVELOPMENT.adoc, buildSrc/src/main/kotlin/pklNativeBuild.gradle.kts, pkl-core/pkl-core.gradle.kts
Support running native tests with "gw testNative" for consistency with "gw test".
=> Add Gradle task "testNative"

pkl-core/src/main/java/org/pkl/core/packages/PackageResolvers.java
Access to field "isClosed" must be guarded.
=> Fix concurrency bug in PackageResolvers

pkl-core/src/test/files/LanguageSnippetTests/input/api/reflectedDeclaration.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/api/reflectedDeclaration.pcf, stdlib/reflect.pkl
I didn't test all possibilities of reflecting values, but all the ones I tested worked.
=> make reflected values renderable

DEVELOPMENT.adoc, README.adoc
Add some more cross linking and the artifact url
=> Minor development/contributing/ci doc links / additions

buildSrc/settings.gradle.kts
The warning was introduced by 1e502009.
=> Fix Gradle build warning

README.adoc
I also experimented with other styles, such as `float=left`, but couldn't make them look quite right in the IntelliJ preview.
=> Add Pkl logo to README

patches/graalVm23.patch
This fixes an issue that is perventing our patch from from being applied.
=> Fix patch file

.circleci/config.pkl, .circleci/config.yml
Change resource size to "small".
=> Use smaller compute resource for patch test

docs/docs.gradle.kts, docs/modules/java-binding/examples/JavaConfigExample.java, docs/modules/kotlin-binding/examples/KotlinConfigExample.kt
Fixes wrong data types (string instead of list), and also adds these examples to our unit tests.
Closes #368
=> Fix java/kotlin usage examples

docs/modules/pkl-cli/pages/index.adoc
Also, quote the URLs for better shell compatibility
=> Fix links for downloading snapshot executables

pkl-core/src/main/java/org/pkl/core/stdlib/base/MergeSort.java, pkl-core/src/test/files/LanguageSnippetTests/input/api/list.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/api/list.pcf
Fix for https://github.com/apple/pkl/issues/393#issue-2224982881
=> Fix MergeSort.java

CODE_OF_CONDUCT.md
=> Convert CODE_OF_CONDUCT to Markdown

docs/modules/language-reference/pages/index.adoc, pkl-core/src/main/java/org/pkl/core/ast/expression/member/InvokeMethodVirtualNode.java, pkl-core/src/main/java/org/pkl/core/ast/expression/member/InvokeSuperMethodNode.java, pkl-core/src/main/java/org/pkl/core/ast/expression/primary/ResolveVariableNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/Member.java
For details see the commit messages.
=> Improve method.isConst() checks

pkl-core/src/main/java/org/pkl/core/project/ProjectPackager.java, pkl-core/src/main/resources/org/pkl/core/errorMessages.properties
=> Fix: fatal error when chart location is invalid

pkl-cli/pkl-cli.gradle.kts
Fixes an issue where native builds will try to install GraalVM for the wrong architecture.
Closes #450
=> Don't install GraalVM for an architecture that can't be built 

pkl-core/src/main/java/org/pkl/core/http/package-info.java, pkl-core/src/test/kotlin/org/pkl/core/http/RequestCapturingClient.kt
* Add a package-info.java with NonnullByDefault annotation
* Make RequestCapturingClient return a response to satisfy the type checker
CC @translatenix
=> Declare members of http package NonnullByDefault

pkl-core/src/main/java/org/pkl/core/module/ModuleKeys.java, pkl-core/src/test/files/LanguageSnippetTests/output/projects/project1/globbing.pcf
This fixes an issue where globbing resources within a local dependency fails to match anything.
=> Fix local dependency globbing

.circleci/config.pkl, .circleci/config.yml
This policy is no longer necessary.
=> Clean up unnecessary CI logic

docs/modules/pkl-gradle/partials/gradle-codegen-properties.adoc, pkl-gradle/src/main/java/org/pkl/gradle/PklPlugin.java, pkl-gradle/src/main/java/org/pkl/gradle/spec/CodeGenSpec.java, pkl-gradle/src/main/java/org/pkl/gradle/task/CodeGenTask.java, pkl-gradle/src/main/java/org/pkl/gradle/task/JavaCodeGenTask.java, pkl-gradle/src/main/java/org/pkl/gradle/task/KotlinCodeGenTask.java, pkl-gradle/src/test/kotlin/org/pkl/gradle/JavaCodeGeneratorsTest.kt, pkl-gradle/src/test/kotlin/org/pkl/gradle/KotlinCodeGeneratorsTest.kt
This changes the property to match the name of the CLI flag.
FYI @netvl
=> Change Gradle property from "packageMapping" to "renames"

docs/modules/language-reference/pages/index.adoc
I believe my update is correct; my apologies if I'm wrong and have wasted your time.
=> [typo] a consts cannot be assigned/amended

docs/modules/release-notes/pages/0.26.adoc, docs/modules/release-notes/pages/changelog.adoc
To be merged after 0.26.2 is released.
=> Import release notes for 0.26.2

pkl-core/src/main/java/org/pkl/core/ast/expression/unary/ImportGlobMemberBodyNode.java, pkl-core/src/main/java/org/pkl/core/ast/expression/unary/ReadGlobMemberBodyNode.java, pkl-core/src/test/files/LanguageSnippetTests/input/basic/importGlob.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/basic/readGlob.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/basic/importGlob.pcf, pkl-core/src/test/files/LanguageSnippetTests/output/basic/readGlob.pcf
This fixes an issue where a PklBugException is thrown when a globbed read/import is amended.
Closes https://github.com/apple/pkl/issues/606
=> Fix: thrown error globbed import/read is amended

docs/modules/release-notes/pages/0.26.adoc, docs/modules/release-notes/pages/changelog.adoc
To be merged after release is complete
=> Cherry pick 0.26.3 release notes

docs/modules/language-reference/pages/index.adoc
This content is "reverse engineered" entirely from using the language and is not an interpretation of the code, so it may be missing or misconstruing things. Please let me know if anything needs adjusting!
=> [docs] Document object instantiation

DEVELOPMENT.adoc, docs/modules/language-reference/pages/index.adoc
Includes
* #624 
* #625 
* #623 
* #614
* #618
* #613
=> [docs] Cherry pick documentation into 0.26 release branch

docs/modules/language-reference/pages/index.adoc
Cherrypicked from #680 which merged into `release/0.26`.
=> Improve let-expression examples

pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt
- don't generate copy methods for abstract classes
- precisely determine if copy method needs override modifier (tricky)
Fixes #569
=> codegen-kotlin: Fix generation of copy() methods

README.adoc
Motivation: Discoverability, convenience
=> List Pkl GitHub repositories in README

pkl-core/src/main/java/org/pkl/core/runtime/VmNull.java
=> Remove `isMappingDefault` on `VmNull`

pkl-core/src/test/files/LanguageSnippetTests/input/api/semverModule.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/api/semverModule.pcf, stdlib/semver.pkl
Fix `isLessThan` logic between semvers
Also: adjust binary expressions to adhere to style guide
Closes https://github.com/apple/pkl/issues/772
=> Fix semver comparison logic

docs/antora.yml, docs/modules/ROOT/partials/component-attributes.adoc, docs/modules/release-notes/pages/0.28.adoc, docs/modules/release-notes/pages/changelog.adoc, docs/modules/release-notes/pages/index.adoc, docs/nav.adoc, gradle.properties, jbang-catalog.json, pkl-core/src/main/java/org/pkl/core/runtime/VmLanguage.java, stdlib/Benchmark.pkl, stdlib/DocPackageInfo.pkl, stdlib/DocsiteInfo.pkl, stdlib/EvaluatorSettings.pkl, stdlib/Project.pkl, stdlib/analyze.pkl, stdlib/base.pkl, stdlib/json.pkl, stdlib/jsonnet.pkl, stdlib/math.pkl, stdlib/platform.pkl, stdlib/protobuf.pkl, stdlib/reflect.pkl, stdlib/release.pkl, stdlib/semver.pkl, stdlib/settings.pkl, stdlib/shell.pkl, stdlib/test.pkl, stdlib/xml.pkl, stdlib/yaml.pkl
=> Start dev iteration

pkl-core/src/main/java/org/pkl/core/ast/member/ElementOrEntryNode.java
PRs https://github.com/apple/pkl/pull/789 and https://github.com/apple/pkl/pull/837 being merged caused a compile error; this fixes them.
=> Fix compile error

gradle/wrapper/gradle-wrapper.properties, gradlew
Run with `./gradlew wrapper --gradle-version=8.12 --gradle-distribution-sha256-sum 7a00d51fb93147819aab76024feece20b6b84e420694101f276be952e08bef03`
=> Update Gradle to 8.12

docs/modules/release-notes/pages/0.27.adoc, docs/modules/release-notes/pages/changelog.adoc
In preparation for tomorrow's release
=> Add release notes for 0.27.2

pkl-core/src/main/java/org/pkl/core/SecurityManagers.java
Nested jars built by spring boot can possibly represent classpath resource URIs as "jar:nested:".
This changes Pkl to by default trust them with the same level as modulepath URIs.
=> Allow jar:nested: URIs in default security manager

docs/modules/release-notes/pages/0.27.adoc, docs/modules/release-notes/pages/changelog.adoc
To be merged after 0.27.2 is released
=> Import release notes for 0.27.2

pkl-tools/pkl-tools.gradle.kts
=> Simplify inputs for `javadocJar`

docs/modules/ROOT/pages/evolution-and-roadmap.adoc, docs/modules/release-notes/pages/index.adoc, docs/nav.adoc
To be cherry-picked into release/0.27
=> [docs] Add documetation about release/evolution/roadmap

docs/modules/language-reference/pages/index.adoc
=> Add docs for various keywords

pkl-gradle/src/main/java/org/pkl/gradle/task/BasePklTask.java, pkl-gradle/src/main/java/org/pkl/gradle/task/ModulesTask.java
=> Make Truffle use fallback runtime in Gradle plugin

buildSrc/src/main/kotlin/pklFatJar.gradle.kts, pkl-tools/pkl-tools.gradle.kts
Also, add some logic to test start the shadow jar.
Fixes #999
=> Fix shadow jar logic

pkl-cli/pkl-cli.gradle.kts
=> Allow native-image flags to be passed through from Gradle properties

docs/modules/release-notes/pages/0.28.adoc, docs/modules/release-notes/pages/changelog.adoc, jbang-catalog.json
To be merged after 0.28.1 release
=> Cherry pick 0.28.1

docs/modules/release-notes/pages/0.28.adoc, docs/modules/release-notes/pages/changelog.adoc, jbang-catalog.json
To be merged after 0.28.2 is out
=> Add release notes for 0.28.2

pkl-commons-test/src/main/files/packages/birds@0.5.0/birds@0.5.0.json, pkl-commons-test/src/main/files/packages/fruit@1.0.5/fruit@1.0.5.json, pkl-commons-test/src/main/kotlin/org/pkl/commons/test/PackageServer.kt, pkl-core/src/test/files/LanguageSnippetTests/input/packages/packages1.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/packages/packages2.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/projects/project4/PklProject.deps.json, pkl-core/src/test/files/LanguageSnippetTests/output/packages/packages2.pcf, pkl-doc/src/main/kotlin/org/pkl/doc/DocPackageInfo.kt, pkl-doc/src/main/kotlin/org/pkl/doc/DocScope.kt, pkl-doc/src/main/kotlin/org/pkl/doc/PageGenerator.kt, pkl-doc/src/test/files/DocGeneratorTest/output/com.package1/1.2.3/index.html, pkl-doc/src/test/files/DocGeneratorTest/output/localhost(3a)0/birds/0.5.0/Bird/index.html, pkl-doc/src/test/files/DocGeneratorTest/output/localhost(3a)0/birds/0.5.0/index.html
Package dependencies have wrong links sometimes due to how the URL is built.
=> Fix doc dependency link

pkl-core/src/test/files/LanguageSnippetTests/input/modules/invalidModule1.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/modules/invalidModule1.err, pkl-parser/src/main/java/org/pkl/parser/syntax/Module.java, pkl-parser/src/test/kotlin/org/pkl/parser/ParserComparisonTest.kt
=> Fix crash due to parse error in module header

pkl-config-java/src/main/java/org/pkl/config/java/ConfigEvaluatorBuilder.java, pkl-core/src/main/java/org/pkl/core/http/HttpClient.java, pkl-core/src/main/java/org/pkl/core/service/ExecutorSpiImpl.java, pkl-executor/src/main/java/org/pkl/executor/ExecutorOptions.java, pkl-executor/src/main/java/org/pkl/executor/spi/v1/ExecutorSpiOptions3.java, pkl-executor/src/test/kotlin/org/pkl/executor/EmbeddedExecutorTest.kt, stdlib/EvaluatorSettings.pkl
* Add ability to set HTTP builder in ConfigEvaluatorBuilder
* Add ability to set rewrites in executor API
* Polish documentation
=> Polish http rewrites

pkl-parser/src/test/kotlin/org/pkl/parser/ParserComparisonTest.kt
This was broken on main after the formatter merge.
=> Fix broken test
