docs/modules/pkl-cli/pages/index.adoc
The download URL mismatched with the architecture for macOS builds.
=> Fix macOS download URL mismatch

docs/modules/language-tutorial/pages/03_writing_a_template.adoc
Map values of `agenda` should have a `name` instead of a `title` to be consistent with the `TutorialPart` module.
Fixes #11.
=> Fix minor discrepancy in workshop example

pkl-doc/src/main/resources/org/pkl/doc/scripts/search-worker.js, pkl-doc/src/test/files/DocGeneratorTest/output/scripts/search-worker.js
Fixes two issues:
1. The search-index.js script doesn't get imported in the docsite
2. The regexes aren't accessible to the function, thanks to hoisting
=> Fix broken search on pkldoc

pkl-core/src/main/java/org/pkl/core/PklInfo.java
This adds a trailing slash that was missing from the documentation homepage.
=> Fix documentation homepage

docs/modules/language-reference/pages/index.adoc, docs/modules/pkl-cli/pages/index.adoc
A bunch of examples were trying to invoke `pkl` on a file directly without using a subcommand.
Also fix the docs for `pkl eval -x` that used the wrong key.
=> Fix missing `pkl eval` subcommand in documentation examples

docs/modules/pkl-cli/pages/index.adoc
Based on the Language Reference concatenation example, `To concatenate strings, use the + (plus) operator, as in "abc" + "def" + "ghi".`. I double checked the lang ref for a `+=` operator and it doesn't appear to be defined.
=> fix concat operator and string typo

docs/modules/pkl-cli/pages/index.adoc
The example config content:
bird {
species = "Pigeon"
diet = "Seeds"
}
parrot {
species = "Parrot"
diet = "Berries"
}
But in the 'Loading Modules' example, 'bird.name' was used which in most cases will return an error for those following;
–– Pkl Error ––
Cannot find property name in object of type Dynamic.
1 | bird.name
^^^^^^^^^
at  (repl:pkl1)
Available properties:
default
diet
species
=> update 'Loading Modules' example to match config contents

buildSrc/src/main/kotlin/BuildInfo.kt, pkl-cli/pkl-cli.gradle.kts, pkl-core/pkl-core.gradle.kts
This improves the development experience for (WSL) Linux users. They can now run "./gradlew buildNative" without having a musl toolchain installed. In this case, only the dynamically linked executable will be built.
=> Only build static executable if musl toolchain is installed

docs/modules/language-reference/pages/index.adoc
These examples on the documentation where not clear and also didn't have valid syntax.
=> Update Hidden Properties documentation example

DEVELOPMENT.adoc
- remove "Setup Gradle on your system" (too vague and doesn't seem necessary)
- remove "gw pkldoc" (obsolete)
- improve docs for common build commands
=> Update development instructions

docs/modules/language-reference/pages/index.adoc, docs/modules/language-tutorial/pages/02_filling_out_a_template.adoc
At docs/modules/language-tutorial/pages/02_filling_out_a_template.adoc:35, I guess it makes at least some sense to keep it as is (it was prettier before my change), but I believe the proposed change makes it ever so slightly more accurate, making it a tiny bit easier for first-time readers to understand the nomenclature.
(Absolutely love this tool btw! 😍)
=> Minor documentation fixes

pkl-core/src/test/kotlin/org/pkl/core/LanguageSnippetTestsEngine.kt
This allows to "Run all Tests" in IntelliJ without getting lots of test errors because "pkl-alpine-linux-amd64" etc. doesn't exist.
=> Don't run JUnit tests for non-existing native executables

docs/modules/language-tutorial/pages/02_filling_out_a_template.adoc
Running through the tutorial, the amending was stated in the tutorial text but not visible in the tutorial output since `parrot.pkl` was replacing all the members of `pigeon.pkl`.
=> Add details to show amending leaving untouched properties intact

docs/modules/language-tutorial/pages/02_filling_out_a_template.adoc
Currently, typed objects are only briefly mentioned in the sentence stating that (typed) objects cannot be amended with new properties, only existing ones. This is unnecessarily confusing since all examples up until that point have been concerned with dynamic objects. Since the tutorial goes on to amend a dynamic object with a new property in the next section, a reader who isn't yet aware there are two types of objects might be confused by what seems to be a contradiction.
=> Introduce Typed objects before referring to them

docs/modules/introduction/pages/use-cases.adoc
corrected typo maintian -> maintain
=> Typo: Update use-cases.adoc

pkl-cli/src/main/kotlin/org/pkl/cli/CliDownloadPackageCommand.kt, pkl-cli/src/test/kotlin/org/pkl/cli/CliDownloadPackageCommandTest.kt
This is a backwards-incompatible change. I assume this isn't a public API because it isn't documented.
PS: `CliDownloadPackageCommandTest` is very flaky for me. I believe the reason is that `PackageServer` binds to a hardcoded port (12110).
=> Fix typo in constructor parameter name

docs/modules/language-reference/pages/index.adoc
`const` is not reserved, it has a meaning already. And `match` is not a keyword at all.
=> Update Reserved keywords list in the Language Reference

docs/modules/language-reference/pages/index.adoc
Example given on pkl docs for `-m` is incorrect.
```sh
pkl eval -m output/ pigeon.pkl
–– Pkl Error ––
Cannot find module `../pkl_schemas/pigeon.pkl`.
```
Should be
```sh
pkl eval -m output/ birds.pkl
output/birds/pigeon.json
output/birds/parrot.yaml
```
=> Fix multiple output example code

pkl-core/pkl-core.gradle.kts
This fixes many "unknown symbol" errors in Java source files.
=> Mark generated/truffle as generated source dir in IntelliJ

pkl-core/src/main/java/org/pkl/core/packages/PackageResolvers.java
The only call site already resolved the path against tmpDir.
=> Fix almost-bug in PackageResolvers

docs/modules/java-binding/pages/codegen.adoc, docs/modules/java-binding/pages/pkl-config-java.adoc, docs/modules/kotlin-binding/pages/codegen.adoc, docs/modules/kotlin-binding/pages/pkl-config-kotlin.adoc, docs/modules/pkl-core/pages/index.adoc, docs/modules/pkl-doc/pages/index.adoc
Replace the legacy "compile" scope with "implementation". This matches Maven Central's recommended syntax:
https://central.sonatype.com/artifact/org.pkl-lang/pkl-core
=> Update Gradle syntax in docs

pkl-config-java/src/main/java/org/pkl/config/java/InvalidMappingException.java
Hi pkl team
I hope this message finds you well. 
I've made some enhancements to the code in the InvalidMappingException class located at 
pkl-config-java/src/main/java/org/pkl/config/java/InvalidMappingException.java. 
The changes aim to improve code consistency by utilizing the final modifier for certain variables.
I would love to get involved in this new exciting language.
The best
Manuel
=> Improve code consistency with final modifier.

docs/modules/language-tutorial/pages/03_writing_a_template.adoc
On line 170 I believe the filename that is meant to be referenced is`pklTutorialPart3.pkl` as there is not a `pklTutorial.pkl` file mentioned in this section. I also made some fun changes with the template using the date that pkl was publicly released.
=> writing a template documentation fixes

buildSrc/src/main/kotlin/pklPublishLibrary.gradle.kts
This small change fixes a bug introduced by the `validatePom` task within the `pklPublishLibrary` plugin. When running project-wide tasks like `./gradle tasks`, projects which don't provide a POM fail the build, because the `generatePomFileForLibraryPublication` cannot be found, but it is expected to be present.
With this change applied, `validatePom` only runs if the task `generatePomFileForLibraryPublication` is present in a given project.
Fixes and closes apple/pkl#215
=> Skip POM validation for unpublished projects

bench/bench.gradle.kts, docs/docs.gradle.kts, pkl-cli/pkl-cli.gradle.kts, pkl-codegen-java/pkl-codegen-java.gradle.kts, pkl-codegen-kotlin/pkl-codegen-kotlin.gradle.kts, pkl-commons-cli/pkl-commons-cli.gradle.kts, pkl-commons-test/pkl-commons-test.gradle.kts, pkl-config-java/pkl-config-java.gradle.kts, pkl-config-kotlin/pkl-config-kotlin.gradle.kts, pkl-core/pkl-core.gradle.kts, pkl-doc/pkl-doc.gradle.kts, pkl-executor/pkl-executor.gradle.kts, pkl-gradle/pkl-gradle.gradle.kts, pkl-server/pkl-server.gradle.kts, pkl-tools/pkl-tools.gradle.kts, settings.gradle.kts
This change activates the `TYPESAFE_PROJECT_ACCESSORS` feature preview in Gradle, and switches to such accessors instead of string-based project references, where possible
Originally previewed in apple/pkl#204
- chore: activate `TYPESAFE_PROJECT_ACCESSORS` feature
- chore: switch to using project references instead of `project(":<...>")` in most circumstances
=> Use Gradle typed project accessors

pkl-core/src/main/java/org/pkl/core/packages/PackageResolvers.java
It is customary to separate elements with a semicolon.
=> Tweak User-Agent header

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/pklJavaLibrary.gradle.kts, buildSrc/src/main/kotlin/pklKotlinLibrary.gradle.kts, gradle/libs.versions.toml
Add a fix to make Version Catalog symbols visible within the `buildSrc` plugins, and then move tool versions (Google Java Format and ktfmt) into the catalog.
Originally previewed as part of apple/pkl#204.
- fix: make version catalog accessible from `buildSrc` plugins
- chore: declare `googleFormatVersion` in version catalog
- chore: declare `ktfmt` in version catalog
=> Move tool versions to Version Catalog

pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/CliKotlinCodeGeneratorOptions.kt
Fixes and closes apple/pkl#191:
> In [CliKotlinCodeGeneratorOptions](https://github.com/apple/pkl/blob/3b2feb45cf47ef97c6db38b2cb5af4ecc713f447/pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/CliKotlinCodeGeneratorOptions.kt#L41-L42), the implementSerializable property is not copied to the KotlinCodegenOptions, in effect meaning it cannot be toggled to true.
=> Fix dropped `implementSerializable` flag

pkl-cli/src/main/kotlin/org/pkl/cli/CliPackageDownloader.kt, pkl-cli/src/main/kotlin/org/pkl/cli/CliProjectCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/CliProjectPackager.kt, pkl-cli/src/main/kotlin/org/pkl/cli/CliProjectResolver.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/DownloadPackageCommand.kt, pkl-cli/src/test/kotlin/org/pkl/cli/CliPackageDownloaderTest.kt
CliDownloadPackageCommand -> CliPackageDownloader (consistent with CliProjectPackager/CliProjectResolver) CliAbstractProjectCommand -> CliProjectCommand (consistent with CliCommand)
As I learned yesterday, I'm touching a public API here. Let me know if this is acceptable.
=> Rename some CLI classes for consistency

pkl-server/pkl-server.gradle.kts
Before: "test" runs no tests, "unitTests" runs all tests
After : "test" runs all tests
=> Fix Gradle test tasks in pkl-server

pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/CliKotlinCodeGeneratorOptions.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt, pkl-gradle/src/main/java/org/pkl/gradle/PklPlugin.java, pkl-gradle/src/main/java/org/pkl/gradle/spec/KotlinCodeGenSpec.java, pkl-gradle/src/main/java/org/pkl/gradle/task/KotlinCodeGenTask.java, pkl-gradle/src/test/kotlin/org/pkl/gradle/KotlinCodeGeneratorsTest.kt
Adds a setting to the Kotlin code generator which acts as a prefix for the target Kotlin package during codegen.
This has been filed on top of #192 to avoid conflicts.
- feat(gradle): `kotlinPackage` property in gradle plugin
- feat(codegen): use `kotlinPackage` as prefix for kotlin codegen
- fix: pin version of `kotlinx.html` and `kotlinx.serialization`
- test(codegen): add tests for custom kotlin package
- test(gradle): add tests for generating with custom kotlin package
=> Add codegen setting governing Kotlin package

buildSrc/src/main/kotlin/pklFatJar.gradle.kts
This allows two libraries that use Truffle to coexist in a host application.
=> Add com.oracle.truffle to shaded libs

pkl-core/src/main/java/org/pkl/core/ast/VmModifier.java, pkl-core/src/test/files/LanguageSnippetTests/input-helper/api/reflect/BaseModule.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/api/reflect1.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/api/reflect1.pcf, stdlib/reflect.pkl
This fixes an issue where the reflect API does not show `fixed` or `const` modifiers on a property.
=> Fix: add missing "const" and "fixed" modifiers to reflect API

docs/modules/kotlin-binding/pages/codegen.adoc, docs/modules/pkl-cli/pages/index.adoc
Java 11 is the minimum version, rather than 8.
=> Docs fix: Java 8 is not supported

docs/modules/language-reference/pages/index.adoc
Adjusts documentation to remove legacy `Container` type, and add the rest of the generic types in the stdlib.
=> Docs fix: Container is not a type, add more types

pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/CliKotlinCodeGeneratorOptions.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt, pkl-gradle/src/main/java/org/pkl/gradle/PklPlugin.java, pkl-gradle/src/main/java/org/pkl/gradle/spec/KotlinCodeGenSpec.java, pkl-gradle/src/main/java/org/pkl/gradle/task/KotlinCodeGenTask.java, pkl-gradle/src/test/kotlin/org/pkl/gradle/KotlinCodeGeneratorsTest.kt
This reverts commit 7f404fff490e2dd883cf9683c21f6fd38fd84518.
The package is derived from the module name.
Having `module com.example.Foo` in Pkl
will create Kotlin `package com.example`.
=> Revert "Add setting for Kotlin package to codegen (#194)"

.circleci/config.pkl, .circleci/config.yml
* Prevent build_artifacts.txt files from being published as GitHub releases
* Bump version to 1.0.2; make PRBs not depend on flakey pr-approval job
=> Improve CircleCI builds

docs/modules/language-reference/pages/index.adoc
Fix missing closing quotes in 'Local Dependencies' section of index.adoc to ensure syntax correctness.
=> Fix missing closing quotes in Local dependencies part of language-reference doc

pkl-core/src/main/java/org/pkl/core/http/HttpClientBuilder.java, pkl-core/src/main/java/org/pkl/core/service/ExecutorSpiImpl.java, pkl-core/src/main/java/org/pkl/core/util/Exceptions.java, pkl-core/src/test/kotlin/org/pkl/core/http/HttpClientTest.kt, pkl-core/src/test/kotlin/org/pkl/core/util/ExceptionsTest.kt, pkl-executor/pkl-executor.gradle.kts, pkl-executor/src/test/kotlin/org/pkl/executor/EmbeddedExecutorTest.kt
* pkl-excutor tests: copy 0.25.0 distribution into pkl-executable/build
* Use `IoUtils.getPklHomeDir` in HttpClientBuilder
* Simplify Exceptions.java
* Enable testing for older pkl-executor distribution
(CC @translatenix)
=> Clean up http-client changes

pkl-core/src/main/java/org/pkl/core/ast/VmModifier.java, pkl-core/src/main/java/org/pkl/core/ast/builder/AstBuilder.java, pkl-core/src/test/files/LanguageSnippetTests/input-helper/modules/Birds.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/modules/amendModule6.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/modules/amendModule6.pcf
This fixes an assertion error that gets thrown if:
1. A module declares a class as abstract
2. An amending module does not instantiate a value that is an instance of that class
3. Java assertions are turned on
Underneath the hood, the modifiers of the class/typelias object member is considered different from the modifiers on the VmClass/VmTypeAlias values.
The object model skips forcing any explicitly members that are explicitly declared hidden, abstract, or local.
However, it _should_ evaluate any abstract classes found in a module. So, it's incorrect to apply the same modifiers on the class to the object member.
=> Fix amending module with abstract class

pkl-commons-test/pkl-commons-test.gradle.kts
Make sure that declaring a dependency on project `pkl-commons-test` suffices to have its test fixtures generated.
This fix should work reliably.
However, there may be a more idiomatic way to achieve the same result.
=> Fix build issue where test fixtures weren't generated

.circleci/config.pkl, .circleci/config.yml, .circleci/jobs/BuildNativeJob.pkl, .circleci/jobs/DeployJob.pkl, .circleci/jobs/GradleCheckJob.pkl, .circleci/jobs/GradleJob.pkl, .circleci/jobs/SimpleGradleJob.pkl
Adds logic to build (but not deploy) commits on the release branch.
This is so we have CI coverage for new patch releases of older versions.
=> Add CI to release/x.x branch

.circleci/config.pkl, .circleci/config.yml
Temporary workaround for now because our CI policy requires it.
=> Add approval for release/x.x branch

build.gradle.kts, buildSrc/src/main/kotlin/pklFatJar.gradle.kts, buildSrc/src/main/kotlin/pklHtmlValidator.gradle.kts, buildSrc/src/main/kotlin/pklJavaLibrary.gradle.kts, buildSrc/src/main/kotlin/pklPublishLibrary.gradle.kts, pkl-cli/pkl-cli.gradle.kts, pkl-commons-test/pkl-commons-test.gradle.kts, pkl-config-java/pkl-config-java.gradle.kts, pkl-config-kotlin/pkl-config-kotlin.gradle.kts, pkl-core/pkl-core.gradle.kts, stdlib/stdlib.gradle.kts
This switches Gradle scripts to use `layout.buildDirectory` instead of hard-coded "build".
=> Use layout.buildDirectory

patches/graalVm23.patch
This fixes an issue where Gradle fails to build because of Java/Kotlin getting mismatching versions when targeting macOS/aarch64.
=> Fix buildSrc Kotlin/Java compat

docs/modules/java-binding/examples/JavaConfigExample.java
There is no method `evaluateText` in `ConfigEvaluator` or `ConfigEvaluatorImpl`.
=> Removed undeclared method reference in examples.

pkl-cli/src/test/kotlin/org/pkl/cli/CliProjectPackagerTest.kt, pkl-core/src/main/java/org/pkl/core/project/ProjectPackager.java
fixes #318 
The solution is simply:
We only collect "RegularFiles".
In this case we filter out directories of that returning `List`.
Since the regular files already includes the path (obviously), the packaging still works as expected 🚀
=> Do not package empty directories

buildSrc/src/main/kotlin/pklPublishLibrary.gradle.kts
The maven publish plugin isn't setting up dependencies correctly, and we are getting errors like:
"Task ':pkl-config-java:publishFatJarPublicationToMavenLocal' uses
this output of task ':pkl-config-java:signLibraryPublication' without
declaring an explicit or implicit dependency."
This adds a workaround for this type of error.
=> Add workaround for configuration error during maven publish

gradle.properties
Speed ups developing process *a bit* 🙃 
See also https://docs.gradle.org/current/userguide/build_cache.html
Some statistics:
> Running `./gradlew clean build console=plain`
**Cache disabled**
clean build 1m 2s
clean build 53s
clean build 51s
*260 actionable tasks: 248 executed, 12 up-to-date*
**Cache enabled**
clean build 48s
clean build 37s
clean build 37s
*260 actionable tasks: 153 executed, 69 from cache, 38 up-to-date*
=> Enable Gradle build caching

pkl-core/src/main/java/org/pkl/core/project/ProjectPackager.java
It's unnecessary to load and instantiate an expensive Calendar class to compute this constant.
jshell> new GregorianCalendar(1980, Calendar.FEBRUARY, 1, 0, 0, 0).getTimeInMillis();
$1 ==> 318240000000
=> Eliminate unnecessary use of GregorianCalendar

pkl-cli/src/test/kotlin/org/pkl/cli/CliProjectPackagerTest.kt, pkl-commons-test/src/main/kotlin/org/pkl/commons/test/InputOutputTestEngine.kt, pkl-commons-test/src/main/kotlin/org/pkl/commons/test/PackageServer.kt, pkl-core/src/main/java/org/pkl/core/http/JdkHttpClient.java, pkl-core/src/test/files/LanguageSnippetTests/input/packages/packages1.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/packages/packages2.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/packages/redirects.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/packages/packages2.pcf, pkl-core/src/test/files/LanguageSnippetTests/output/packages/redirects.pcf, pkl-core/src/test/kotlin/org/pkl/core/LanguageSnippetTestsEngine.kt
- Change HttpClient to follow all redirects except HTTPS to HTTP.
- Run language snippet tests with --no-cache and real PackageServer instead of pre-seeded cache. This increases HTTP test coverage and enables testing of package redirects.
- Change PackageServer to return 301 for request paths starting with /HTTP301/ and 307 for request paths starting with /HTTP307/.
- Update some outdated test package checksums that apparently weren't verified.
=> Follow HTTP redirects

pkl-core/src/main/java/org/pkl/core/http/HttpClientInitException.java
PklException is mainly used to indicate errors during evaluation of Pkl code. It isn't a suitable superclass for HttpClientInitException.
=> Change HttpClientInitException to extend RuntimeException

pkl-doc/src/main/kotlin/org/pkl/doc/DocPackageInfo.kt, pkl-doc/src/test/files/DocGeneratorTest/output/localhost:0/birds/0.5.0/Bird/index.html, pkl-doc/src/test/files/DocGeneratorTest/output/localhost:0/birds/0.5.0/allFruit/index.html, pkl-doc/src/test/files/DocGeneratorTest/output/localhost:0/birds/0.5.0/catalog/index.html, pkl-doc/src/test/files/DocGeneratorTest/output/localhost:0/fruit/1.1.0/Fruit/index.html
The more principled solution is to have `importUri` be a `URI` instead of a `String` and to test its scheme.
Generally, the problem is that `URI::resolve` can not assume fragments to be a path (and that it discards fragments altogether).
=> Avoid resolving paths on fragments

docs/modules/release-notes/pages/changelog.adoc
This adds the release notes for 0.25.3 into CHANGELOG.
To be merged after 0.25.3 is released.
=> Import release notes for 0.25.3

docs/modules/bindings-specification/pages/index.adoc
Using `xref` turns these links into fragments.
=> Fix links to pkl-go and pkl-swift repos

pkl-core/src/main/java/org/pkl/core/ast/type/TypeNode.java, pkl-core/src/test/files/LanguageSnippetTests/input/types/typeAlias2.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/types/typeAlias2.pcf
This fixes an issue where the frame's owner/receiver are not reset if a type test on a typealias fails.
=> Ensure owner and receiver are reset after executing alias

pkl-core/src/main/java/org/pkl/core/module/ModulePathResolver.java, pkl-core/src/main/java/org/pkl/core/packages/PackageResolvers.java, pkl-core/src/main/java/org/pkl/core/project/ProjectPackager.java, pkl-core/src/main/java/org/pkl/core/util/IoUtils.java
Use `Files.newInputStream(path)` instead of `new FileInputStream(path.toFile())` and `Files.newOutputStream(path)` instead of `new FileOutputStream(path.toFile())`.
=> Use Files.newInputStream()/newOutputStream() where appropriate

docs/modules/ROOT/pages/index.adoc
Motivation:
The standard library docs are some of the most important docs but currently very hard to find. I've noticed that even advanced users have never heard of them and complain about "zero docs".
=> Add quick link to standard library docs

pkl-gradle/src/main/java/org/pkl/gradle/task/EvalTask.java
Rationale: "Output file names are known only after execution" isn't a legitimate reason to make this task untracked because the output directory is known in this case. This is no different from (say) the `JavaCompile` task, where only the class file output directory is known upfront. Forum discussion didn't reveal another reason why this task should be untracked.
=> Turn EvalTask into a tracked Gradle task

pkl-core/src/main/java/org/pkl/core/stdlib/yaml/ParserNodes.java, pkl-core/src/test/files/LanguageSnippetTests/output/api/yamlParser3.pcf
The initialSize in EconomicsMaps.create() is not the actual stored size, hence the accurate size is not determined until ObjectMembers are added after addMembers() called.
Since the size set during the creation of VmListing cannot be changed afterwards, the size of node.getValue() is used instead of members' size.
=> Fix the sequence length in the YAML parser

.circleci/config.pkl, .circleci/config.yml, .circleci/jobs/GradleCheckJob.pkl, buildSrc/src/main/kotlin/BuildInfo.kt, buildSrc/src/main/kotlin/GradleVersionInfo.kt, gradle/libs.versions.toml, patches/graalVm23.patch, pkl-codegen-java/src/test/kotlin/org/pkl/codegen/java/CliJavaCodeGeneratorTest.kt, pkl-core/src/main/java/org/pkl/core/resource/ResourceReaders.java, pkl-core/src/main/java/org/pkl/core/util/IoUtils.java, pkl-core/src/test/kotlin/org/pkl/core/util/HttpUtilsTest.kt, pkl-core/src/test/kotlin/org/pkl/core/util/IoUtilsTest.kt, pkl-tools/src/dummy/java/org/pkl/tools/Empty.java
JDK 21 is an LTS release that reached GA in September 2023.
=> Support building with JDK 21

stdlib/base.pkl
* Class-based converters are covariant, not invariant.
* Between multiple class-based converters, the most specific one wins.
Also: format doc comment according to 100 character max column width.
=> Fix documentation about ValueRenderer converters

pkl-core/src/main/java/org/pkl/core/ast/expression/generator/GeneratorSpreadNode.java, pkl-core/src/test/files/LanguageSnippetTests/input/errors/cannotAssignFixedProperty3.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/errors/cannotAssignFixedProperty3.err
When using spread syntax with typed object, properties that are fixed or const cannot be assigned or amended.
This should be checked in the checkTypedProperty() function.
=> Cannot assign property with fixed/const in spread

docs/modules/language-reference/pages/index.adoc
Changes include:
1. Spelling correction addressing #401
2. Grammer and punctuation corrections.
3. Rephrasing of some harder-to-read sentences. Most are simple one or two-word additions to make reading less jarring.
4. Changed hyphenation occurrences that included &ndash; rather than a regular hyphen-dash.
=> Spelling and grammar corrections to Language Reference

pkl-core/src/main/java/org/pkl/core/util/IoUtils.java
`class System` gets initialized at build time through `native-image` and added to the heap. We initialize everything at build time via the `--initialize-at-build-time=` flag.
=> Suppress warnings for `System.getProperty("line.separator")`

docs/docs.gradle.kts, pkl-cli/pkl-cli.gradle.kts, pkl-core/pkl-core.gradle.kts, pkl-server/pkl-server.gradle.kts
This pull requests enables caching for the native image building task and improves the caching effectiveness of some of the test tasks in the project.
1. the native image building is a generic `Exec` tasks for which caching needs to be enabled explicitly (see [docs](https://docs.gradle.org/current/userguide/build_cache.html#using_the_runtime_api)) as the build tool doesn't have natively have enough information to cache it effectively -- furthermore some steps need to be taken to normalize the classpath (JARs come with an embedded timestamp in their manifest and this needs to be ignored), as well as not rely on absolute paths
2. while tests are usually cacheable, path relativity needs to be added as a property to ensure the results can be retrieved from a cache without relying on the …
=> Enable caching of native image building and test tasks

pkl-core/src/main/java/org/pkl/core/runtime/TestRunner.java, pkl-core/src/test/kotlin/org/pkl/core/EvaluateTestsTest.kt
This should make the `<file>-expected.pcf` file a bit easier to read when examples contain quotes or backslashes.
=> Enable useCustomStringDelimiters for pkl test example output

docs/modules/kotlin-binding/pages/pkl-config-kotlin.adoc
compile(...) is not supported in Gradle Kotlin DSL by default. Changed it to implementation(...). Also moved Kotlin to the first tab in Gradle, because it is now the default Gradle Language
=> Fix gradle dependency declare issue & order

docs/modules/pkl-cli/pages/index.adoc
Per #237 notes about Windows platform support for the install docs.   Assuming this is what was desired will add additional docs to --allowed-modules and update https://github.com/apple/pkl-jvm-examples/pull/9 .  https://github.com/apple/pkl-jvm-examples/pull/9 is mostly not related to Windows, just likely Windows users may run into issues around its usage. 
I am not sure what items other than allowed-modules may specifically have path related issues or if there is a better place to discuss Windows paths in more detail.
I have not found a way to sparse-checkout (cone or no-cone) or ignore the two invalid window path areas:
- pkl-doc/src/test/files/DocGeneratorTest/output/*
- pkl-core/src/test/files/LanguageSnippetTests/input-helper/globtest/*
=> Windows installation notes

.circleci/config.pkl, .circleci/config.yml, .circleci/jobs/SimpleGradleJob.pkl, DEVELOPMENT.adoc, docs/modules/java-binding/pages/codegen.adoc, docs/modules/java-binding/pages/pkl-config-java.adoc, docs/modules/kotlin-binding/pages/codegen.adoc, docs/modules/kotlin-binding/pages/pkl-config-kotlin.adoc, docs/modules/pkl-cli/pages/index.adoc, docs/modules/pkl-core/pages/index.adoc, docs/modules/pkl-doc/pages/index.adoc, docs/modules/pkl-gradle/pages/index.adoc, pkl-cli/pkl-cli.gradle.kts, pkl-cli/src/test/kotlin/org/pkl/cli/CliEvaluatorTest.kt, pkl-core/src/main/java/org/pkl/core/http/JdkHttpClient.java, pkl-gradle/pkl-gradle.gradle.kts, pkl-gradle/src/main/java/org/pkl/gradle/PklPlugin.java, settings.gradle.kts
* Fix CI job for bench and gradle-compatibility
* Fix documentation issues around Java compatibility (Java 11 -> Java 17)
* Bump minimum Gradle version to 8.1
=> JDK version bump cleaups

.circleci/config.yml, pkl-cli/src/main/kotlin/org/pkl/cli/Main.kt
According to https://github.com/oracle/graal/issues/3398, the bug necessitating this workaround was fixed in October 2022.
Note: I can't test this, but hopefully CI can.
=> Remove obsolete Alpine Linux workaround

pkl-cli/pkl-cli.gradle.kts, pkl-core/pkl-core.gradle.kts
- Move all conditional configuration to the `assembleNative` and `testNative` "root" tasks
- Also pick default macOS tasks according to CPU architecture (wasn't the case before, but I assume it makes sense)
=> Improve conditional configuration of native build tasks

.circleci/config.yml, .circleci/jobs/DeployJob.pkl
The CI is failing for deploy-snapshot job.
Ref: https://app.circleci.com/pipelines/github/apple/pkl/760/workflows/b39c0772-56db-4ba3-a5bc-edef38e25bc2/jobs/4203
The reason is that using image is JDK11.0, but we specify the 17.0
=> [Fix][CI] Use JDK 17 image for deploy-snapshot job

docs/modules/java-binding/pages/codegen.adoc, docs/modules/java-binding/pages/pkl-config-java.adoc, docs/modules/kotlin-binding/pages/codegen.adoc, docs/modules/kotlin-binding/pages/pkl-config-kotlin.adoc, docs/modules/pkl-core/pages/index.adoc, docs/modules/pkl-doc/pages/index.adoc, docs/modules/pkl-gradle/pages/index.adoc
Following up on https://github.com/apple/pkl/pull/411; this PR changes the order of the Groovy and Kotlin tabs in the documentation, making Kotlin the new default.
=> Swap Kotlin/Groovy tab order in documentation

pkl-core/src/main/java/org/pkl/core/PClassInfo.java, pkl-core/src/main/java/org/pkl/core/runtime/SettingsModule.java, pkl-core/src/main/java/org/pkl/core/settings/PklSettings.java, pkl-core/src/main/resources/org/pkl/core/errorMessages.properties, pkl-core/src/test/kotlin/org/pkl/core/settings/PklSettingsTest.kt
This is technically a breaking change, but follows the intended use-case and documentation of settings.
* Require that the global settings file at `~/.pkl/settings.pkl` amends stdlib module `pkl:settings`, or otherwise sets `output.value` to an instance of `pkl.Settings`.
* Simplify the object mapping of `PklSettings.java`
=> Require global settings file to use `pkl:settings`

docs/modules/bindings-specification/pages/message-passing-api.adoc, pkl-server/src/main/kotlin/org/pkl/server/ClientModuleKeyFactory.kt, pkl-server/src/main/kotlin/org/pkl/server/ClientResourceReader.kt, pkl-server/src/test/kotlin/org/pkl/server/ServerTest.kt
In messages "List Resources Response" and "List Modules Response", if `pathElements` and `error` are both null, default to an empty list.
=> Handle `null` pathElements gracefully in message passing API

pkl-cli/src/main/kotlin/org/pkl/cli/CliRepl.kt, pkl-commons-cli/src/main/kotlin/org/pkl/commons/cli/CliCommand.kt, pkl-core/src/main/java/org/pkl/core/EvaluatorBuilder.java, pkl-core/src/main/java/org/pkl/core/module/ModuleKeyFactories.java, pkl-core/src/main/java/org/pkl/core/module/ModuleKeys.java, pkl-core/src/main/java/org/pkl/core/module/ResolvedModuleKeys.java, pkl-core/src/main/java/org/pkl/core/service/ExecutorSpiImpl.java, pkl-server/src/main/kotlin/org/pkl/server/Server.kt
GenericUrl is a catch-all that uses URL.openConnection(). Since we now have special handling of HTTP urls, it makes more sense to put it in its own module key.
Those that don't use the Http module key specifically but use `GenericUrl` will still be able to fetch `http` urls, but it would use the standard `URL.openConnection` implementation. This works the same as `file:` URIs; if only the `GenericUrl` module key factory is used, Pkl can still load `file:` uris.
(FYI @translatenix)
=> Introduce specialized ModuleKey(Factory) for `http` uris

docs/modules/language-tutorial/pages/02_filling_out_a_template.adoc
Looking through the [Ammending](https://pkl-lang.org/main/current/language-tutorial/02_filling_out_a_template.html#amending) section of the "Filling out a template" tutorial, it seemed like the code snippets and the textual explanation didn't align nicely. I've updated the code snippets to match the text surrounding them as it seemed like the text was the correct one. Here's a summary of changes:
1. Swapped out the relationship between stock and wood pigeon - it appeared like wood pigeon should be amending stock pigeon rather than the other way around.
2. Added `kingdom`, `clade`, and `order` to `stockPigeon.taxonomy` as the text was referencing those fields, but those were missing from the code snippet.
3. Updated the output snippet to reflect the code reorganization.
=> Update amending example

pkl-doc/src/main/kotlin/org/pkl/doc/PageGenerator.kt, pkl-doc/src/main/kotlin/org/pkl/doc/RuntimeDataGenerator.kt, pkl-doc/src/test/files/DocGeneratorTest/output/com.package1/1.2.3/index.html, pkl-doc/src/test/files/DocGeneratorTest/output/com.package2/4.5.6/index.html, pkl-doc/src/test/files/DocGeneratorTest/output/localhost(3a)0/birds/0.5.0/index.html, pkl-doc/src/test/files/DocGeneratorTest/output/localhost(3a)0/fruit/1.1.0/index.html
The stdlib is an implicit dependency for every package. Showing this as a dependency is unnecessary noise.
Before:
After:
=> Omit showing stdlib as dependency in pkldoc

pkl-doc/src/main/kotlin/org/pkl/doc/DocGenerator.kt
It references something that isn't present and should be removed.
```
❯ rg packageInfos
pkl-doc/src/main/kotlin/org/pkl/doc/DocGenerator.kt
48:   * A function to resolve imports in [modules], [packageInfos], and [docsiteInfo].
```
=> Remove documentation references to `packageInfos`

.circleci/config.yml, .circleci/jobs/BuildNativeJob.pkl, pkl-cli/pkl-cli.gradle.kts, pkl-commons-test/src/main/kotlin/org/pkl/commons/test/PklExecutablePaths.kt, pkl-core/pkl-core.gradle.kts, pkl-core/src/test/kotlin/org/pkl/core/LanguageSnippetTestsEngine.kt, pkl-server/pkl-server.gradle.kts, pkl-server/src/test/kotlin/org/pkl/server/AbstractServerTest.kt, pkl-server/src/test/kotlin/org/pkl/server/JvmServerTest.kt, pkl-server/src/test/kotlin/org/pkl/server/NativeServerTest.kt, pkl-server/src/test/kotlin/org/pkl/server/TestTransport.kt
This is supercedes and closes #455
Thanks to @translatenix for doing 99% of the work here
* Remove unnecessary `--add-opens` by deferring initialization of MessagePack library at build time
* Use quick build mode for 40% faster compilation and 20% smaller executable when not creating release builds
* Add test for native executables when running in server mode
=> Improve configuration of native image compilation

.circleci/config.yml, .circleci/jobs/BuildNativeJob.pkl, pkl-server/pkl-server.gradle.kts
Fix an issue where the CI job attempts to install the wrong executable when on macOS/aarch64.
Also, adjusts native test definitions in pkl-server to match pkl-core.
=> Fix native tests in CircleCI

docs/modules/language-reference/pages/index.adoc, pkl-core/src/main/java/org/pkl/core/ast/builder/SymbolTable.java, pkl-core/src/test/files/LanguageSnippetTests/input/errors/const/constTypeAliasConstraint.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/errors/const/constTypeAliasConstraint.err, stdlib/Project.pkl
This adds a language change that requires references from typealiases to the enclosing module to be `const`.
This is required because typealiases are not late-bound.
Rationale is laid out in [SPICE-0007](https://github.com/apple/pkl-evolution/pull/8).
Also:
* Update documentation to reflect new rules.
* Fix `Project.pkl`; mark method `const` to not break said rule.
=> Require references from typealiases to be const

.gitattributes
Now that Pkl syntax highlighting is available on GitHub, we can remove the Groovy association with these files.
This also adds changes to mark `*.pcf` and `PklProject` files as Pkl.
=> Use Pkl syntax highlighting instead of Groovy

docs/modules/java-binding/pages/codegen.adoc, docs/modules/java-binding/partials/cli-codegen-options.adoc, docs/modules/pkl-gradle/partials/gradle-codegen-properties.adoc, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/CliJavaCodeGeneratorOptions.kt, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/JavaCodeGenerator.kt, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/Main.kt, pkl-codegen-java/src/test/kotlin/org/pkl/codegen/java/CliJavaCodeGeneratorTest.kt, pkl-codegen-java/src/test/kotlin/org/pkl/codegen/java/InMemoryJavaCompiler.kt, pkl-codegen-java/src/test/kotlin/org/pkl/codegen/java/JavaCodeGeneratorTest.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/CliKotlinCodeGeneratorOptions.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/Main.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/CliKotlinCodeGeneratorTest.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/InMemoryKotlinCompiler.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt, pkl-commons/src/main/kotlin/org/pkl/commons/NameMapper.kt, pkl-commons/src/main/kotlin/org/pkl/commons/PackageMapper.kt, pkl-commons/src/test/kotlin/org/pkl/commons/NameMapperTest.kt, pkl-gradle/pkl-gradle.gradle.kts, pkl-gradle/src/main/java/org/pkl/gradle/PklPlugin.java, pkl-gradle/src/main/java/org/pkl/gradle/spec/CodeGenSpec.java, pkl-gradle/src/main/java/org/pkl/gradle/task/CodeGenTask.java, pkl-gradle/src/main/java/org/pkl/gradle/task/JavaCodeGenTask.java, pkl-gradle/src/main/java/org/pkl/gradle/task/KotlinCodeGenTask.java, pkl-gradle/src/test/kotlin/org/pkl/gradle/JavaCodeGeneratorsTest.kt, pkl-gradle/src/test/kotlin/org/pkl/gradle/KotlinCodeGeneratorsTest.kt
See #456 for motivation.
Closes #456
=> Implemented package mapping for Java/Kotlin code generation

pkl-commons-cli/src/main/kotlin/org/pkl/commons/cli/CliCommand.kt
This fixes an issue where an error coming from loading a project file is shown as a PklBugException.
There were two problems here:
1. `proxyAddress` needs to be a lazy value, because it can try to load a PklProject
2. accessing `proxyAddress` can throw a `PklException`, so it needs to be within the try/catch
=> Catch PklException errors coming from project load

docs/modules/pkl-cli/pages/index.adoc, docs/modules/pkl-cli/partials/cli-common-options.adoc, pkl-cli/src/test/kotlin/org/pkl/cli/CliEvaluatorTest.kt, pkl-commons-cli/src/main/kotlin/org/pkl/commons/cli/CliBaseOptions.kt, pkl-commons-cli/src/main/kotlin/org/pkl/commons/cli/CliCommand.kt, pkl-commons-cli/src/main/kotlin/org/pkl/commons/cli/commands/BaseOptions.kt, pkl-gradle/src/main/java/org/pkl/gradle/PklPlugin.java, pkl-gradle/src/main/java/org/pkl/gradle/spec/BasePklSpec.java, pkl-gradle/src/main/java/org/pkl/gradle/task/BasePklTask.java
Rationale: "proxy" can mean very different things (e.g. [Proxy](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Proxy.html) in Java). This makes the flag name more specific.
CLI:
* `--proxy` -> `--http-proxy`
* `--no-proxy` -> `--http-no-proxy`
Gradle:
* `proxyAddress` -> `httpProxy`
* `noProxy` -> `httpNoProxy`
=> Change CLI flag and Gradle name for proxy options

pkl-cli/pkl-cli.gradle.kts
The release build is broken, because of the empty string in `CommandLineArgumentProvider`. This PR fixes that.
=> Fix release build gradle setup

docs/modules/release-notes/pages/0.26.adoc
Add a contributor name who was missing from acknowledgements.
I will cherry-pick this into release/0.26 once merged into main.
=> docs: add contributor for 0.26 release

pkl-cli/pkl-cli.gradle.kts
We currently have to use `NATIVE_IMAGE_DEPRECATED_BUILDER_SANITATION` to let builds pass in Homebrew. This is because `native-image` runs its child processes (such as the platform-dependent C compiler) in a "clean" environment. In Homebrew, such compilers (`clang`, `gcc`, etc) are wrapper scripts that first check the Homebrew environment is intact.
GraalVM folks have warned that `NATIVE_IMAGE_DEPRECATED_BUILDER_SANITATION` will go away.
This PR preserves all environment variables starting with `HOMEBREW_` for the inner `native-image` environment.
=> Pass `HOMEBREW_*` environment variables on through `native_image`

pkl-cli/pkl-cli.gradle.kts
Use the most compatible architecture; for example, x86-64 instead of x86-64-v3.
=> Use compatible architecture in native executables

.circleci/config.pkl, .circleci/config.yml
This fixes our CI tests on main. It mitigates an issue where the current RC is borked right now (see https://github.com/gradle/gradle/issues/29696)
=> Only run Gradle compatibility tests against releases in CI

pkl-doc/src/main/resources/org/pkl/doc/styles/pkldoc.css, pkl-doc/src/test/files/DocGeneratorTest/output/styles/pkldoc.css
The current hard cutoff in the docs often results in people not realising that the doc box can be expanded, and often resulting in confusion because the most helpful examples are often in the module doc box.
This change uses some simple CSS tweaks to replace the hard cut-off with a visualfade, so it's obvious that there's content hidden out of view. Doing this required removing the CSS transition, as it hard to correctly transition the height property of CSS element of unknown target height. But the improved discoverablility of the doc content seems like a worthwhile tradeoff.
Before:
After:
=> Add CSS to make top doc box have a fade, rather than hard cutoff

pkl-core/src/main/java/org/pkl/core/stdlib/base/StringNodes.java, pkl-core/src/test/files/LanguageSnippetTests/input/api/string.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/api/string.pcf
A Int literal can include sequence of "_" like below.
```pkl
a = 1_2__3___
```
However, `String#toInt()` method cannot parse such string.
```pkl
a = "1_2__3__".toInt()
```
This PR is to fix this issue.
Refs: https://github.com/apple/pkl/discussions/577#discussion-6927552
=> Allow to `String#toInt()` to parse a string including "__"

pkl-core/src/main/java/org/pkl/core/stdlib/base/StringNodes.java, pkl-core/src/test/files/LanguageSnippetTests/input/api/string.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/api/string.pcf
The logic is the same as the Pkl parser
=> Support `_` in String[toInt|toIntOrNull|toFloat|toFloatOrNull]

pkl-core/src/main/java/org/pkl/core/packages/PackageResolvers.java, pkl-core/src/test/kotlin/org/pkl/core/packages/PackageResolversTest.kt
This fixes a possible race condition where multiple processes download the same package into the same temp dir.
The issue here is that we are using the _same_ filename when creating these temp files. Because of this, two concurrent processes can possibly run into `FileAlreadyExistsException` when attempting to create the temporary file.
This fixes the problem by using the `Files#createTempFile` API to ensure that these filenames are unique.
Closes https://github.com/apple/pkl/issues/583
=> Fix race condition when concurrently downloading packages

pkl-commons-cli/src/main/kotlin/org/pkl/commons/cli/commands/BaseOptions.kt, pkl-commons-cli/src/test/kotlin/org/pkl/commons/cli/BaseCommandTest.kt
This fixes a bug where a property set as `-p foo=` would be parsed as `"true"` instead of `""`.
=> Fix property parsing bug in the cli

pkl-cli/src/main/kotlin/org/pkl/cli/CliEvaluator.kt, pkl-gradle/src/main/java/org/pkl/gradle/task/BasePklTask.java, pkl-gradle/src/main/java/org/pkl/gradle/task/EvalTask.java, pkl-gradle/src/main/java/org/pkl/gradle/task/ModulesTask.java, pkl-gradle/src/test/kotlin/org/pkl/gradle/EvaluatorsTest.kt
This makes Gradle track `getOutputPaths()` and `getMultipleFileOutputPaths`. These represent the actual outputs of the EvalTask.
=> Make EvalTask track resolved output paths

pkl-gradle/src/main/java/org/pkl/gradle/task/ModulesTask.java
This is a port of a fix that was included in https://github.com/apple/pkl/pull/403.
Note: this is intentionally landing directly in the release/0.26 branch.
=> Fix usage of `file()` notation with Pkl Gradle plugin on Windows

pkl-gradle/src/test/kotlin/org/pkl/gradle/EvaluatorsTest.kt
The tests were using [simple Kotlin DSL assignments](https://blog.gradle.org/simpler-kotlin-dsl-property-assignment), a feature only available in Gradle 8.2 and onwards. Thus, they were breaking our tests on Gradle 8.1 (the minimum Gradle version for the pkl-gradle plugin).
Tested locally:
```
gw :pkl-gradle:compatibilityTestReleases
Type-safe project accessors is an incubating feature.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD SUCCESSFUL in 8m …
```
=> Fix: make Gradle tests compatible with Gradle 8.1

docs/modules/language-reference/pages/index.adoc
I've experience a few users missing this section of the documentation because they searched "optional". This terminology is common in other languages (eg. Swift, Python). This adds a sentence to the documentation to ease search-ability.
=> [docs] Add mention of "optional" to nullable types section

DEVELOPMENT.adoc
Correct the link for `ANTLR 4 Documentation` (404 - page not found).
=> [docs] Correct the link for `ANTLR 4 Documentation` (404 - page not found).

docs/modules/language-reference/pages/index.adoc
The primary goal here is to have this section appear first (or at least high) when using the docs search for "function". I'm not fully satisfied with this solution, so open to alternative suggestions.
=> [docs] Improve searchability of "Methods" section

pkl-commons-cli/src/main/kotlin/org/pkl/commons/cli/commands/BaseOptions.kt, pkl-commons-cli/src/test/kotlin/org/pkl/commons/cli/BaseCommandTest.kt
=> Fix parsing of external property values containing `=`

docs/modules/bindings-specification/pages/message-passing-api.adoc, pkl-server/src/main/kotlin/org/pkl/server/ClientModuleKeyFactory.kt, pkl-server/src/main/kotlin/org/pkl/server/ClientResourceReader.kt, pkl-server/src/test/kotlin/org/pkl/server/AbstractServerTest.kt
In messages "Read Resource Response" and "Read Module Response", if `contents` and `error` are both null, default to an empty byte array/string.
This resolves one of the issues reported in #656
=> Handle `null` contents gracefully in message passing API

pkl-core/src/main/java/org/pkl/core/stdlib/base/StringNodes.java, pkl-core/src/test/files/LanguageSnippetTests/input/api/string.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/api/reflectedDeclaration.pcf, pkl-core/src/test/files/LanguageSnippetTests/output/api/string.pcf, stdlib/base.pkl
Open to naming input here!
* Java, Kotlin, and Swift use an overload of `String.split` for this
* Golang calls this [`SplitN`](https://pkg.go.dev/strings#SplitN)
* Python uses a defaulted argument on `str.split`
=> Add `String.splitLimit` API

docs/modules/language-reference/pages/index.adoc
Because I did not understand what a `Let Expression` should be and the example code was more confusing as explanatory, I changed the format of the examples a little bit and changed the result.
- It should be clear that the example is just one code-line
- I tried out the example (`pkl eval...`) and get a little bit different result
=> Update Let Expressions Examples

pkl-core/src/main/java/org/pkl/core/module/ModuleKeyFactories.java
Previously, some factories used case-sensitive comparison, for no apparent reason.
=> Use case-insensitive comparison for module URI schemes

pkl-core/src/main/java/org/pkl/core/util/GlobResolver.java, pkl-core/src/main/java/org/pkl/core/util/IoUtils.java
Motivation:
Speed up the test that verifies enforcement of the limit for glob pattern resolution (invalidGlobImport6.pkl).
Changes:
- Set a lower limit if test mode is enabled.
- Change static field to static method to prevent compile-time evaluation by native-image.
Result:
Test takes 0.5 instead of 15 seconds to run (on my machine).
Fixes #691.
=> Set lower limit for glob pattern resolution in test mode

pkl-core/src/main/java/org/pkl/core/ast/builder/AstBuilder.java, pkl-core/src/main/java/org/pkl/core/packages/PackageResolvers.java
Both methods replace all occurrences.
The difference is that String.replaceAll interprets its first argument as a regex.
=> Replace some usages of java.lang.String.replaceAll with String.replace

buildSrc/src/main/kotlin/pklAllProjects.gradle.kts, buildSrc/src/main/kotlin/pklJavaLibrary.gradle.kts
Motivation:
Spotless tasks take minutes instead of seconds to complete. This greatly slows down `gw spotlessApply`, `gw check`, and `gw build`.
Changes:
- Use more efficient glob expressions for inclusion filters (`target()`).
- Avoid the need for exclusion filters (`targetExclude()`).
Result:
Spotless tasks complete in seconds instead of minutes. As a concrete example, repeated invocation of `gw spotlessApply` completes in 2 instead of 122 seconds on my laptop.
=> Fix build performance issues of spotless tasks

pkl-executor/src/main/java/org/pkl/executor/EmbeddedExecutor.java, pkl-executor/src/main/java/org/pkl/executor/ExecutorException.java
Only when catching an exception from evaluation can we decorate the `ExecutorException` with Pkl version information (all other occurrences are pre-resolution failures or failure-to-resolve). That's why this PR adds an extra constructor.
=> Add version of resolved Pkl distribution to `ExecutorException`

pkl-core/src/main/java/org/pkl/core/runtime/VmUtils.java, pkl-core/src/test/files/LanguageSnippetTests/input/errors/listingTypeCheckError6.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/errors/listingTypeCheckError7.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/errors/mappingTypeCheckError10.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/errors/mappingTypeCheckError9.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/errors/listingTypeCheckError6.err, pkl-core/src/test/files/LanguageSnippetTests/output/errors/listingTypeCheckError7.err, pkl-core/src/test/files/LanguageSnippetTests/output/errors/mappingTypeCheckError10.err, pkl-core/src/test/files/LanguageSnippetTests/output/errors/mappingTypeCheckError9.err
The addresses the following case:
```
local l1: Listing<String> = new { 1 }
l2: Listing<Int> = (l1) { 2 }
```
The member in `l1` should be checked against its owner; to check against `Listing<String>`.
=> Fix typecheck error on Listing/Mapping

pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt
Motivation:
Don't generate code that isn't useful.
Changes:
- Don't generate equals/hashCode/toString/copy methods for abstract classes.
- Don't make abstract classes serializable.
Result:
- Less code is generated.
- Fixes #713.
Note:
codegen-java does the same for stateless classes, but it also makes them non-instantiable.
codegen-kotlin generates stateless regular classes far less often than codegen-java.
=>     codegen-kotlin: Don't generate equals/hashCode/toString/copy/:Serializable for abstract classes

pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/JavaCodeGenerator.kt, pkl-codegen-java/src/test/kotlin/org/pkl/codegen/java/JavaCodeGeneratorTest.kt, pkl-codegen-java/src/test/resources/org/pkl/codegen/java/Inheritance.jva
Motivation:
* Currently, the condition for generating `equals/hashCode/toString` methods is "generated class declares properties". As a result, classes that don't declare properties inherit these methods from their generated superclasses. However, generated `equals` and `toString` methods aren't designed to be inherited and will either fail or produce wrong results when called for a subclass.
* Currently, the condition for generating `with` methods is "class is not abstract". However, it isn't useful to generate `with` methods for non-instantiable non-abstract classes.
* Currently, the condition for making classes serializable is "class is not a module class". However, it isn't useful to make non-instantiable non-module classes serializable, and it is useful to make instantiable module …
=> codegen-java: Change condition for generating equals/hashCode/toString/with/Serializable

pkl-cli/src/main/kotlin/org/pkl/cli/CliTestRunner.kt, pkl-cli/src/test/kotlin/org/pkl/cli/CliTestRunnerTest.kt, pkl-core/src/main/java/org/pkl/core/runtime/TestResults.java, pkl-core/src/main/java/org/pkl/core/runtime/TestRunner.java, pkl-core/src/main/java/org/pkl/core/stdlib/test/report/JUnitReport.java, pkl-core/src/main/java/org/pkl/core/stdlib/test/report/SimpleReport.java, pkl-core/src/test/kotlin/org/pkl/core/EvaluateTestsTest.kt, pkl-gradle/src/test/kotlin/org/pkl/gradle/TestsTest.kt
Add some basic test stats to the test runner output for both SimpleReport and JUnitReport:
- number of tests that pass/fail
- % of success
- number of assertions within each test that pass / fail
=> Improve testing with stats and errors per test section

pkl-gradle/src/test/kotlin/org/pkl/gradle/TestsTest.kt
Just rebased some PRs on main and they're all failing in the pkl-gradle tests. This PR fixes the expectations, which changed with what I think is #695
=> Fix test failures on main

pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/JavaCodeGenerator.kt, pkl-codegen-java/src/test/kotlin/org/pkl/codegen/java/JavaCodeGeneratorTest.kt
Last codegen PR for now. :-)
Motivation:
Currently, the condition for making a generated Java class instantiable is "class is neither abstract nor stateless".
(An instantiable class receives a public constructor and equals/hashCode/toString/with methods.)
This is inconsistent with Pkl and codegen-kotlin, both of which support instantiation of stateless classes.
Changes:
Widen condition for making a class instantiable to "class is neither abstract nor a stateless final module class".
This is consistent with codegen-kotlin, which generates object declarations (only) for stateless final module classes.
Result:
Stateless classes are instantiable in Pkl, codegen-java, and codegen-kotlin.
=> codegen-java: Make stateless classes instantiable

pkl-core/src/main/java/org/pkl/core/ast/type/TypeNode.java, pkl-core/src/test/files/LanguageSnippetTests/input/basic/as2.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/basic/as2.pcf
For example, `Listing<UInt16>` is equivalent to `Listing<UInt16>`, but not to `Listing<UInt32>`.
=> Fix lazy type checking of UInt types

pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt
Motivation:
- Java serialization makes as much sense for module classes as it does for regular classes.
- Offer same Java serialization support as codegen-java.
Changes:
- Move generation of `appendProperty` method and serialization code
into new method `generateCompanionRelatedCode`.
- Improve/fix generation of serialization code.
Result:
Java serialization is also supported for module classes.
=> codegen-kotlin: Support Java serialization of module classes

pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/JavaCodeGenerator.kt, pkl-codegen-java/src/test/kotlin/org/pkl/codegen/java/JavaCodeGeneratorTest.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt
Motivation:
In Spring Boot 3.0, the annotation type `org.springframework.boot.context.properties.ConstructorBinding` was deprecated in favor of `org.springframework.boot.context.properties.bind.ConstructorBinding`. In 3.2, the old annotation type was removed.
As of 3.0, a `@ConstructorBinding` annotation is no longer required/recommended for configuration classes with a single public constructor.
Changes:
Remove generation of `@ConstructorBinding` annotations in codegen-java and codegen-kotlin.
Result:
- Generated code is compatible with Spring Boot 3.x. (Verified with locally updated pkl-spring.)
- Generated code is no longer compatible with Spring Boot 2.x. To use Pkl 0.27 and later with Spring Boot 2.x, use Pkl 0.26's code generator.
- Fixes #139.
=> codegen-java/kotlin: Support Spring Boot 3.x instead of 2.x

pkl-core/src/main/java/org/pkl/core/service/ExecutorSpiImpl.java, pkl-executor/src/main/java/org/pkl/executor/EmbeddedExecutor.java, pkl-executor/src/test/kotlin/org/pkl/executor/EmbeddedExecutorTest.kt
There are two fixes here:
* pkl-core's `ExecutorSpiImpl` now properly handles project evaluation errors
* pkl-executor's `EmbeddedExecutor` now catches all `RuntimeException`s and transforms them to `ExecutorException` so the `Executor` API contract is upheld.
=>  Correct EmbeddedExecutor to throw ExecutorException instead of PklException when project evaluation fails

docs/modules/pkl-doc/pages/index.adoc
Right now it looks like that (red underline):
I removed the code ticks and replaced them with an underscore to better match the style (see the blue circle 🙃).
=> Replace code tick with italic

pkl-commons-cli/src/main/kotlin/org/pkl/commons/cli/CliCommand.kt, pkl-core/src/main/java/org/pkl/core/EvaluatorBuilder.java, pkl-core/src/main/java/org/pkl/core/externalreader/ExternalReaderMessagePackDecoder.java, pkl-core/src/main/java/org/pkl/core/externalreader/ExternalReaderMessagePackEncoder.java, pkl-core/src/main/java/org/pkl/core/externalreader/ExternalReaderMessages.java, pkl-core/src/main/java/org/pkl/core/externalreader/ExternalReaderProcess.java, pkl-core/src/main/java/org/pkl/core/externalreader/ExternalReaderProcessImpl.java, pkl-core/src/main/java/org/pkl/core/messaging/MessageTransports.java, pkl-core/src/main/java/org/pkl/core/messaging/Messages.java, pkl-core/src/main/java/org/pkl/core/module/ModuleKeys.java, pkl-core/src/main/java/org/pkl/core/resource/ExternalResourceResolver.java, pkl-core/src/main/java/org/pkl/core/resource/ResourceReaders.java, pkl-core/src/main/java/org/pkl/core/util/Readers.java, pkl-server/src/main/kotlin/org/pkl/server/Server.kt
Things I noticed but didn't address in this PR:
* many APIs are missing Javadoc
* libraries shouldn't log directly to std out/err (see `ExternalReaderProcessImpl`)
* some `ExternalReaderProcessException` messages are externalized, others aren't
* `ExternalReaderProcessException` is a checked exception
- it's not clear to me what Pkl's policy on unchecked vs. checked exceptions is
* `new Random().nextLong()` is expensive and has poor randomness (Random should be reused or replaced with counter)
* deprecation of `ModuleKeyFactories.closeQuietly` in favor of `org.pkl.core.util.Readers.closeQuietly` turns package `org.pkl.core.util` into a public API
- private packages keep leaking into public APIs
* `org.pkl.core.module.ResourceReaders` API is (too) tightly coupled to reader protocol via …
=> Polish external reader API/implementation

pkl-core/src/main/java/org/pkl/core/runtime/StackTraceRenderer.java, pkl-core/src/main/java/org/pkl/core/runtime/TestRunner.java, pkl-core/src/main/java/org/pkl/core/runtime/VmExceptionRenderer.java, pkl-core/src/main/java/org/pkl/core/stdlib/test/report/SimpleReport.java, pkl-core/src/main/java/org/pkl/core/util/AnsiStringBuilder.java, pkl-core/src/main/java/org/pkl/core/util/AnsiTheme.java, pkl-core/src/main/java/org/pkl/core/util/StringUtils.java, pkl-core/src/test/kotlin/org/pkl/core/runtime/StackTraceRendererTest.kt, pkl-core/src/test/kotlin/org/pkl/core/util/AnsiStringBuilderTest.kt
- change line numbers from blue to faint to improve legibility on dark backgrounds
- use EnumSet throughout
- move all ANSI classes into package core.util (no need to split them over util and runtime)
- rename AnsiCodingStringBuilder to AnsiStringBuilder
=> Polish ANSI formatting and underlying code

pkl-core/src/main/java/org/pkl/core/ast/builder/AstBuilder.java, pkl-core/src/main/java/org/pkl/core/ast/expression/binary/LetExprNode.java, pkl-core/src/main/java/org/pkl/core/ast/expression/literal/AmendFunctionNode.java, pkl-core/src/main/java/org/pkl/core/ast/expression/member/InvokeMethodDirectNode.java, pkl-core/src/main/java/org/pkl/core/ast/expression/member/InvokeMethodLexicalNode.java, pkl-core/src/main/java/org/pkl/core/ast/expression/member/InvokeMethodVirtualNode.java, pkl-core/src/main/java/org/pkl/core/ast/expression/member/InvokeSuperMethodNode.java, pkl-core/src/main/java/org/pkl/core/ast/expression/member/ResolveMethodNode.java, pkl-core/src/main/java/org/pkl/core/ast/internal/ToStringNode.java, pkl-core/src/main/java/org/pkl/core/ast/lambda/ApplyVmFunction0Node.java, pkl-core/src/main/java/org/pkl/core/ast/lambda/ApplyVmFunction1Node.java, pkl-core/src/main/java/org/pkl/core/ast/lambda/ApplyVmFunction2Node.java, pkl-core/src/main/java/org/pkl/core/ast/lambda/ApplyVmFunction3Node.java, pkl-core/src/main/java/org/pkl/core/ast/lambda/ApplyVmFunction4Node.java, pkl-core/src/main/java/org/pkl/core/ast/lambda/ApplyVmFunction5Node.java, pkl-core/src/main/java/org/pkl/core/ast/member/FunctionNode.java, pkl-core/src/main/java/org/pkl/core/ast/type/IdentityMixinNode.java, pkl-core/src/main/java/org/pkl/core/ast/type/TypeNode.java, pkl-core/src/main/java/org/pkl/core/runtime/VmFunction.java, pkl-core/src/main/java/org/pkl/core/stdlib/base/FunctionNodes.java, pkl-core/src/test/files/LanguageSnippetTests/input/generators/forGeneratorNestedReference.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/generators/forGeneratorNestedReference.pcf
This mitigates an issue where lazy mappings and listings widen an existing bug.
This is a follow-up to https://github.com/apple/pkl/pull/752.
Ideally, when we fix the scoping bug, we also revert this commit.
=> Eagerly check function arguments when called from inside iterable

pkl-core/src/main/java/org/pkl/core/runtime/VmListing.java, pkl-core/src/main/java/org/pkl/core/runtime/VmListingOrMapping.java, pkl-core/src/main/java/org/pkl/core/runtime/VmMapping.java, pkl-core/src/main/java/org/pkl/core/runtime/VmObject.java, pkl-core/src/test/files/LanguageSnippetTests/input/api/mapping.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/listings/equality.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/listings/hashCode.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/mappings/equality.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/mappings/hashCode.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/api/mapping.pcf, pkl-core/src/test/files/LanguageSnippetTests/output/listings/equality.pcf, pkl-core/src/test/files/LanguageSnippetTests/output/listings/hashCode.pcf, pkl-core/src/test/files/LanguageSnippetTests/output/mappings/equality.pcf, pkl-core/src/test/files/LanguageSnippetTests/output/mappings/hashCode.pcf
This fixes issues when a mapping/listing delegates to another mapping/listing.
The core issue is that `cachedValues` is not guaranteed to be the complete set of the object's members; they may be stored on the delegate instead.
Therefore, it's not correct compute hash code and equality based on `cachedValues`. Instead, it's better to use the `getCachedValue()` method, which has the correct logic for looking up the existing cached value.
=> Fix equals/hashCode/hasCachedValue in delegating listings/mappings

docs/modules/release-notes/pages/0.27.adoc
The "number literals" link on the [0.27 release notes](https://pkl-lang.org/main/current/release-notes/0.27.html) is a broken link pointing to a local `file://` URL. I think this should fix it to point to the live docs site (similar to how other doc links are setup).
=> Fix broken link to documentation site in release notes

pkl-commons-test/src/main/kotlin/org/pkl/commons/test/FileTestUtils.kt, pkl-core/src/main/java/org/pkl/core/ast/expression/literal/EntriesLiteralNode.java, pkl-core/src/test/files/LanguageSnippetTests/input/api/listing.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/api/listing.pcf
Motivation:
The following expression evaluates to 2 instead of 1:
`new Listing { "value" } { [0 + 0] = "override" }.length`
Changes:
- fix length computation in EntriesLiteralNode
- improve `api/listing` tests
- make snippet test failures diffable in IntelliJ
Result:
- fixes https://github.com/apple/pkl/issues/780
- improved dev experience in IntelliJ
=> Fix length of listings with computed index

pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/CliKotlinCodeGeneratorOptions.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt, pkl-codegen-kotlin/src/test/resources/org/pkl/codegen/kotlin/Inheritance.kotlin, pkl-codegen-kotlin/src/test/resources/org/pkl/codegen/kotlin/Kdoc.kotlin, pkl-codegen-kotlin/src/test/resources/org/pkl/codegen/kotlin/PropertyTypes.kotlin
Note to reviewers: The second commit is a rename refactoring.
codegen-kotlin: Generate toString() methods consistent with data classes
Motivation:
codegen-kotlin generates a mix of data classes and regular classes.
For regular classes, toString() methods are also generated.
However, the output of generated toString() methods
differs from the output of default toString() methods of data classes.
Changes:
Generate toString() methods that produce the same output
as default toString() methods of data classes.
Result:
- Less and simpler code is generated.
- Object graphs containing a mix of data classes and regular classes are formatted consistently.
- Fixes #717.
=> codegen-kotlin: Generate toString() methods consistent with data classes

pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/JavaCodeGenerator.kt, pkl-codegen-java/src/test/resources/org/pkl/codegen/java/PropertyTypes.jva, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt, pkl-codegen-kotlin/src/test/resources/org/pkl/codegen/kotlin/PropertyTypes.kotlin
codegen-java:
- use `pattern.pattern()` instead of `pattern` in hashCode method
(consistent with equals method)
codegen-kotlin:
- use `regex.pattern` instead of `regex` in hashCode method
(consistent with equals method)
- if a data class has a Regex property, generate not only
an equals method but also a hashCode method
=> codegen-java/kotlin: Fix generation of hashCode methods

pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/CliJavaCodeGenerator.kt, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/CliJavaCodeGeneratorOptions.kt, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/JavaCodeGenerator.kt, pkl-codegen-java/src/test/kotlin/org/pkl/codegen/java/JavaCodeGeneratorTest.kt
The new name is consistent with existing names `JavaCodeGenerator` and `CliJavaCodeGeneratorOptions`.
Backward compatibility is ensured by turning `JavaCodegenOptions` into a (deprecated) type alias.
Second commit: Deprecate `CliJavaCodeGeneratorOptions.toJavaCodegenOptions()`
I suspect this method was a public API by accident.
=> Rename JavaCodegenOptions to JavaCodeGeneratorOptions

pkl-core/src/main/java/org/pkl/core/Member.java, pkl-core/src/main/java/org/pkl/core/Platform.java, pkl-core/src/main/java/org/pkl/core/Release.java, pkl-doc/src/main/kotlin/org/pkl/doc/CliDocGenerator.kt, pkl-doc/src/main/kotlin/org/pkl/doc/DocScope.kt
Note: The handwritten (now deleted) `equals` and `hashCode` methods of class `org.pkl.core.Release` didn't include components `os` and `flavor`. I suspect this was an oversight.
=> Continue conversion of org.pkl.core POJOs to record classes

pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/CliKotlinCodeGenerator.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/CliKotlinCodeGeneratorOptions.kt
Motivation:
`CliKotlinCodeGeneratorOptions.toKotlinCodegenOptions` is an internal method that isn't useful to clients.
=> codegen-kotlin: Deprecate method `toKotlinCodegenOptions` without replacement

pkl-doc/src/main/kotlin/org/pkl/doc/DocGenerator.kt, pkl-gradle/src/main/java/org/pkl/gradle/PklPlugin.java, pkl-gradle/src/main/java/org/pkl/gradle/task/BasePklTask.java, pkl-gradle/src/main/java/org/pkl/gradle/task/ModulesTask.java, pkl-gradle/src/main/java/org/pkl/gradle/utils/PluginUtils.java, pkl-gradle/src/main/java/org/pkl/gradle/utils/package-info.java, pkl-gradle/src/test/kotlin/org/pkl/gradle/PkldocGeneratorsTest.kt
This fixes an issue where certain modules tasks fail due to the plugin attempting to analyze their imports, but the arguments may not actually be Pkl modules.
For example, the pkldoc task accepts entire packages in its "sourceMoules" property.
This changes the gather imports logic to only analyze file-based modules. This is also a performance improvement; non file-based modules are unlikely to import files due to insufficient trust levels.
Closes https://github.com/apple/pkl/issues/791
=> Exclude non file-based modules from synthesized *GatherImports task

buildSrc/src/main/kotlin/pklFatJar.gradle.kts, gradle/libs.versions.toml, pkl-codegen-java/gradle.lockfile, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/JavaCodeGenerator.kt, pkl-config-java/gradle.lockfile, pkl-core/gradle.lockfile, pkl-core/src/generator/kotlin/org/pkl/core/generator/MemberRegistryGenerator.kt, pkl-tools/gradle.lockfile
Motivation:
`com.squareup.javapoet` is EOL. `com.palantir.javapoet` is an actively maintained fork that supports generating record classes.
=> Switch from com.squareup.javapoet to com.palantir.javapoet

pkl-core/src/main/java/org/pkl/core/ast/type/TypeNode.java
This fixes a problem where the delegate chain of type casts for `Listing`/`Mapping` get unreasonably big, even though the type nodes are the same, which may lead to a stack overflow or performance degradation.
Closes #827
=> Fix possible stack overflow in Listing/Mapping type checking

bench/bench.gradle.kts, buildSrc/src/main/kotlin/BuildInfo.kt, buildSrc/src/main/kotlin/InstallGraalVm.kt, buildSrc/src/main/kotlin/pklGraalVm.gradle.kts, gradle/wrapper/gradle-wrapper.properties
Changes:
- Update wrapper by running the following command: ./gradlew wrapper --gradle-version 8.11 --gradle-distribution-sha256-sum 57dafb5c2622c6cc08b993c85b7c06956a2f53536432a30ead46166dbca0f1e9
- Verify wrapper JAR integrity according to: https://docs.gradle.org/current/userguide/gradle_wrapper.html# manually_verifying_the_gradle_wrapper_jar
- Replace usages of deprecated method `Project.exec` with `ExecOperations.exec`
- Convert extension function `Task.configureInstallGraalVm` to task class `InstallGraalVm`
- a task class is the cleanest way to get hold of `ExecOperations`
- Move extension property `BuildInfo.GraalVm.downloadFile` into class `GraalVm`
- Don't apply plugin `pklGraalVm` in project `bench` (unnecessary, now causes error)
=> Update Gradle to 8.11

docs/modules/release-notes/pages/0.27.adoc, docs/modules/release-notes/pages/changelog.adoc
Cherry picked from `release/0.27`.
=> Add release notes for 0.27.1

.circleci/config.pkl, .circleci/config.yml, .circleci/jobs/BuildNativeJob.pkl, .circleci/jobs/DeployJob.pkl, .circleci/jobs/GradleCheckJob.pkl, .circleci/jobs/GradleJob.pkl, .circleci/jobs/SimpleGradleJob.pkl
Don't use the system Java on Windows builds, instead download them from Adoptium.
Also:
* Fail job if curl returns a 4xx status code
* Add java version to `GradleJob`
=> Download JDK for windows build

pkl-core/src/main/java/org/pkl/core/ast/MemberNode.java, pkl-core/src/main/java/org/pkl/core/ast/PklRootNode.java, pkl-core/src/main/java/org/pkl/core/ast/SimpleRootNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/FunctionNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/ListingOrMappingTypeCastNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/LocalTypedPropertyNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/ModuleNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/ObjectMethodNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/PropertyTypeNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/SharedMemberNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/TypeCheckedPropertyNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/TypedPropertyNode.java, pkl-core/src/main/java/org/pkl/core/ast/member/UntypedObjectMemberNode.java, pkl-core/src/main/java/org/pkl/core/ast/repl/ResolveClassMemberNode.java, pkl-core/src/main/java/org/pkl/core/ast/type/IdentityMixinNode.java, pkl-core/src/main/java/org/pkl/core/stdlib/benchmark/MicrobenchmarkNodes.java
Motivation:
- Perform same exception handling for every implementation of PklRootNode.execute().
- Avoid code duplication.
Changes:
- Change PklRootNode.execute() to be a final method that performs exception handling and calls abstract method executeImpl(), which is implemented by subclasses.
- Remove executeBody() methods, which served a similar purpose but were more limited.
- Remove duplicate exception handling code.
Result:
- More reliable exception handling. This should fix known problems such as misclassifying stack overflows as internal errors and displaying errors without a stack trace.
- Less code duplication.
=> Fix exception handling of PklRootNode's

pkl-cli/src/test/kotlin/org/pkl/cli/CliTestRunnerTest.kt, pkl-core/src/main/java/org/pkl/core/stdlib/test/report/SimpleReport.java
fixes #861
According to AI (and javadoc 😅) the problem is that String.format takes Locale.getDefault if not specified. Indeed I have set de-EN on my machine so it takes comma decimals instead of dot decimals. 
~I haven't tested this yet, just created it on mobile...~
This is my macobok setting (not sure if relevant or the correct screen):
If I run the newly added test without `Locale.ROOT` in `SimpleReport`, I get the following error:
Running with that `Locale.ROOT`:
`BUILD SUCCESSFUL in 37s` 🎉 
---
AI summary 
This pull request includes changes to improve locale independence in the `CliTestRunner` and to ensure consistent locale usage in the `SimpleReport` class. The most important changes include adding a locale independence test for `CliTestRunner` and specifying the root locale for …
=> Make Test Report locale independent 

pkl-core/src/main/java/org/pkl/core/stdlib/AbstractRenderer.java, pkl-core/src/main/java/org/pkl/core/stdlib/base/YamlRendererNodes.java, pkl-core/src/main/java/org/pkl/core/stdlib/protobuf/RendererNodes.java, pkl-core/src/main/resources/org/pkl/core/errorMessages.properties, pkl-core/src/test/files/LanguageSnippetTests/input/api/yamlRenderer8.yml.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/api/yamlRenderer8.yml
[YAML (1.2) explicitly allows _any_ value as a mapping key](https://yaml.org/spec/1.2.2/#3211-nodes), just like Pkl! This PR allows all of Pkl's primitive scalars (those that can already be natively rendered in YAML: Int, Float, Boolean, Null) to be rendered as mapping keys by `YamlRenderer`.
This PR does not attempt to allow non-scalar YAML mapping keys (see Example 2.11 at https://yaml.org/spec/1.2.2/#22-structures). This doesn't appear to be a commonly used YAML feature—I've never seen it in the wild—but may be interesting for Pkl to support. If this is desired, it could be taken on as follow-up work, but it might require significant modifications to `YamlRendererNodes.YamlRenderer`.
Resolves #878
=> `YamlRenderer`: allow all primitive scalar types as map keys

buildSrc/src/main/kotlin/ExecutableJar.kt, docs/modules/pkl-cli/pages/index.adoc, pkl-cli/pkl-cli.gradle.kts
This updates the script used to start the executable to support Windows as well.
For Windows support, the executable needs to be named `jpkl.bat`.
No unit tests here, but this is tested on macOS directly, and on Windows in my Parallels instance.
This follows a technique shown by this blog post: https://mill-build.org/blog/5-executable-jars.html. Thanks, @lihaoyi!
=> Support jpkl executable for Windows

docs/modules/language-reference/pages/index.adoc
It's not possible to use external without backticks.
=> Document missing reserved keywords

buildSrc/src/main/kotlin/pklGradlePluginTest.gradle.kts
Currently, we run against every release version, which is taking 20 minutes to run in CI, and this will grow as Gradle creates more releases.
This limits the amount of Gradle versions being tested against; theoretically, only testing against the minimum version and the maximum version should ensure that we are compatible with every version in the range.
=> Only run Gradle compatibility tests against minimum and maximum release

pkl-gradle/pkl-gradle.gradle.kts, pkl-gradle/src/main/java/org/pkl/gradle/PklPlugin.java
The Kotlin 2.0 version upgrade made us incompatible with Gradle 8.1.
Given that Gradle 8.1 is now over 1.5 years old, this drops support for it, and raises the minimum version to 8.2.
=> Bump minimum Gradle version to 8.2

buildSrc/src/main/kotlin/pklGradlePluginTest.gradle.kts, gradle/wrapper/gradle-wrapper.properties, pkl-executor/pkl-executor.gradle.kts, pkl-tools/pkl-tools.gradle.kts
Command used:
```
./gradlew wrapper \
--gradle-version=8.12.1 \
--gradle-distribution-sha256-sum=8d97a97984f6cbd2b85fe4c60a743440a347544bf18818048e611f5288d46c94
```
Release notes: https://docs.gradle.org/8.12.1/release-notes.html
Fixes the following warning:
```
buildSrc/src/main/kotlin/pklGradlePluginTest.gradle.kts:94:16 'create(String, Class<T!>, Action<in T!>): T' is deprecated. Deprecated in Java
```
Fixes warning:
```
pkl-executor/pkl-executor.gradle.kts:71:45: 'files(vararg Dependency!): (Mutable)Set<File!>!' is deprecated. Deprecated in Java
```
Fixes the following warning:
```
pkl-tools/pkl-tools.gradle.kts:55:27: 'creating(KClass<U>, U.() -> Unit): PolymorphicDomainObjectContainerCreatingDelegateProvider<Task!, U>' is deprecated. Use registering instead. See …
```
=> Upgrade gradle to 8.12.1 (from 8.12) and fix some build warnings

pkl-core/src/main/java/org/pkl/core/runtime/VmUtils.java, pkl-core/src/test/files/LanguageSnippetTests/input/basic/constModifier5.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/basic/constModifier5.err
Closes https://github.com/apple/pkl/issues/508
If the object member is const, it only needs to be executed once, and all children in the prototype chain can use its cached value.
There is a possible other optimization here, not included in this PR: we can avoid adding these values to the child object's `cachedMembers`.
=> Optimization: execute const object bodies and typechecks only once

buildSrc/src/main/kotlin/pklFatJar.gradle.kts, pkl-cli/pkl-cli.gradle.kts
SVM (SubstrateVM) compile configuration classes must be included within the `cli` jar to prevent downstream `native-image` builds from failing. Fat JARs cannot be used with `native-image`, so these classes can still safely be excluded here.
Fixes and closes apple/pkl#907
- fix: don't exclude svm classes from `cli` jar
- fix: include svm exclusions in fatjar config
=> fix: downstream `native-image` builds

docs/modules/language-tutorial/pages/02_filling_out_a_template.adoc
Should mean `pigeon` instead of `parrot` as a separate module
=> Fix typo in tutorial

pkl-cli/pkl-cli.gradle.kts
Execute `1 + 1` instead of eval'ing `circleci.pkl` (might cause spurious failures due to requirement on network connection).
=> Run a simple eval script

pkl-cli/src/main/kotlin/org/pkl/cli/Main.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/AnalyzeCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/DownloadPackageCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/EvalCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/ProjectCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/ReplCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/RootCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/ServerCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/TestCommand.kt, pkl-cli/src/test/kotlin/org/pkl/cli/CliMainTest.kt, pkl-cli/src/test/kotlin/org/pkl/cli/CliTestRunnerTest.kt, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/Main.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/Main.kt, pkl-doc/src/main/kotlin/org/pkl/doc/Main.kt, pkl-doc/src/test/kotlin/org/pkl/doc/CliMainTest.kt
This is a minor improvement: all `Command` are now objects, and they register their own subcommands.
=> Turn CLI commands into objects, statically register subcommands

pkl-core/src/main/java/org/pkl/core/ast/expression/member/ReadSuperEntryNode.java, pkl-core/src/main/java/org/pkl/core/runtime/VmFunction.java, pkl-core/src/main/java/org/pkl/core/stdlib/base/StringNodes.java
These call sites should use `ApplyVmFunction1Node` instead.
=> Remove usages of VmFunction#apply(Object)

pkl-cli/src/main/kotlin/org/pkl/cli/Main.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/AnalyzeCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/DownloadPackageCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/EvalCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/ProjectCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/ReplCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/RootCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/ServerCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/TestCommand.kt, pkl-cli/src/test/kotlin/org/pkl/cli/CliMainTest.kt, pkl-cli/src/test/kotlin/org/pkl/cli/CliTestRunnerTest.kt, pkl-doc/src/main/kotlin/org/pkl/doc/Main.kt, pkl-doc/src/test/kotlin/org/pkl/doc/CliMainTest.kt
Making these classes caused native-image to statically initialize them at build time, which included CLI argument default values (like working dir).
This turns them back into classes.
=> Make commands classes instead of objects

docs/modules/language-reference/pages/index.adoc, stdlib/base.pkl
The language reference and stdlib are both slightly incorrect; maps and sets are ordered when iterated on, but unordered in terms of equality.
=> Improve documentation about Set/Map ordering

buildSrc/src/main/kotlin/BuildInfo.kt
This is to allow building Pkl in environments that don't have access to git.
=> Allow -DcommitId flag when building Pkl

docs/modules/language-reference/pages/index.adoc
Found a mistake in the glob pattern documentation: https://pkl-lang.org/main/current/language-reference/index.html#examples
> `*.pc[lf]`  --  Anything suffixed by `.pkl` or `.pcf`
Changed the pattern to `*.pk[lg]`, matching `.pkl` and `.pkg`
=> Fix incorrect glob example

pkl-core/src/main/java/org/pkl/core/ast/builder/AstBuilder.java, pkl-core/src/main/java/org/pkl/core/parser/BaseParserVisitor.java, pkl-core/src/main/java/org/pkl/core/parser/Parser.java, pkl-core/src/main/java/org/pkl/core/parser/ParserVisitor.java, pkl-core/src/main/java/org/pkl/core/parser/ast/ArgumentList.java, pkl-core/src/main/java/org/pkl/core/parser/ast/Class.java, pkl-core/src/main/java/org/pkl/core/parser/ast/ClassMethod.java, pkl-core/src/main/java/org/pkl/core/parser/ast/ClassProperty.java, pkl-core/src/main/java/org/pkl/core/parser/ast/Expr.java, pkl-core/src/main/java/org/pkl/core/parser/ast/ImportClause.java, pkl-core/src/main/java/org/pkl/core/parser/ast/Keyword.java, pkl-core/src/main/java/org/pkl/core/parser/ast/Modifier.java, pkl-core/src/main/java/org/pkl/core/parser/ast/Module.java, pkl-core/src/main/java/org/pkl/core/parser/ast/ModuleDecl.java, pkl-core/src/main/java/org/pkl/core/parser/ast/ObjectBody.java, pkl-core/src/main/java/org/pkl/core/parser/ast/ObjectMember.java, pkl-core/src/main/java/org/pkl/core/parser/ast/Parameter.java, pkl-core/src/main/java/org/pkl/core/parser/ast/ParameterList.java, pkl-core/src/main/java/org/pkl/core/parser/ast/QualifiedIdentifier.java, pkl-core/src/main/java/org/pkl/core/parser/ast/StringConstantPart.java, pkl-core/src/main/java/org/pkl/core/parser/ast/StringPart.java, pkl-core/src/main/java/org/pkl/core/parser/ast/Type.java, pkl-core/src/main/java/org/pkl/core/parser/ast/TypeAlias.java, pkl-core/src/main/java/org/pkl/core/parser/ast/TypeArgumentList.java, pkl-core/src/main/java/org/pkl/core/parser/ast/TypeParameter.java, pkl-core/src/test/files/LanguageSnippetTests/output/projects/badPklProject1/bug.err, pkl-core/src/test/kotlin/org/pkl/core/parser/ANTLRSexpRenderer.kt, pkl-core/src/test/kotlin/org/pkl/core/parser/ParserComparisonTestInterface.kt, pkl-core/src/test/kotlin/org/pkl/core/parser/SexpRenderer.kt, pkl-core/src/test/kotlin/org/pkl/core/parser/SpanComparison.kt
Fix many span calculations that were wrong. Also adds a test that compares spans between the old ANTLR parser and the current one.
=> fix calculation of spans in parser

pkl-cli/src/main/kotlin/org/pkl/cli/commands/AnalyzeCommand.kt, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/Main.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/Main.kt
Missed these three classes.
This prevents the AOT compiler from statically initializing CLI argument default values (like working dir).
=> Make CliktCommands classes

docs/modules/pkl-doc/pages/index.adoc, docs/modules/pkl-gradle/pages/index.adoc, pkl-commons/src/main/kotlin/org/pkl/commons/Paths.kt, pkl-doc/src/main/kotlin/org/pkl/doc/CliDocGenerator.kt, pkl-doc/src/main/kotlin/org/pkl/doc/CliDocGeneratorOptions.kt, pkl-doc/src/main/kotlin/org/pkl/doc/DocGenerator.kt, pkl-doc/src/main/kotlin/org/pkl/doc/Main.kt, pkl-doc/src/test/kotlin/org/pkl/doc/CliDocGeneratorTest.kt, pkl-gradle/src/main/java/org/pkl/gradle/PklPlugin.java, pkl-gradle/src/main/java/org/pkl/gradle/spec/PkldocSpec.java, pkl-gradle/src/main/java/org/pkl/gradle/task/PkldocTask.java
Some systems, for example, GitHub Pages, have trouble with handling symlinks, which breaks the `current` directory links created by Pkldoc. In this PR, we add an alternative mode which creates a full copy of the latest published version contents in the `current` directory instead.
=> Added support for an alternative current dir mode in pkldoc

pkl-core/src/main/java/org/pkl/core/ast/builder/AstBuilder.java, pkl-core/src/main/java/org/pkl/core/ast/type/TypeNode.java, pkl-core/src/main/java/org/pkl/core/ast/type/UnresolvedTypeNode.java, pkl-core/src/main/java/org/pkl/core/runtime/VmLanguage.java, pkl-core/src/main/java/org/pkl/core/runtime/VmLocalContext.java, pkl-core/src/test/files/LanguageSnippetTests/input-helper/classes/MyClass.pkl, pkl-core/src/test/files/LanguageSnippetTests/input-helper/classes/myClass1.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/classes/constraints13.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/classes/constraints14.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/errors/constraintDetails1.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/errors/constraintDetails2.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/errors/constraintDetails3.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/classes/constraints13.pcf, pkl-core/src/test/files/LanguageSnippetTests/output/classes/constraints14.pcf, pkl-core/src/test/files/LanguageSnippetTests/output/errors/constraintDetails1.err, pkl-core/src/test/files/LanguageSnippetTests/output/errors/constraintDetails2.err, pkl-core/src/test/files/LanguageSnippetTests/output/errors/constraintDetails3.err
This changes the language to check all types eagerly when within a type constraint.
This addresses a regression where error messages might show objects that are missing details (see https://github.com/apple/pkl/issues/918).
Another implication of this change is: type constraints are stricter. Now, type annotations will check `Mapping` and `Listing` members if the annotation is executed from a constraint.
This currently does not throw, and will after this change:
```pkl
import "pkl:test"
const local isBirds = (it: Listing<Bird>) -> true
birds: Listing(isBirds) = new { 1; 2; 3 }
class Bird
```
=> Execute typechecks eagerly when within a constraint

pkl-core/src/main/java/org/pkl/core/ast/type/TypeNode.java
Fixes an issue that is preventing the native executable from building
=> Ensure `findOrAddAuxiliarySlot` is not called during compilation

buildSrc/src/main/kotlin/pklGradlePluginTest.gradle.kts
This fixes our Gradle compatibility tests.
Not really sure how to avoid using the deprecated API here.
Filed https://github.com/gradle/gradle/issues/32599 on Gradle.
=> Revert Gradle plugin tests to use deprecated API

pkl-core/src/main/java/org/pkl/core/ast/expression/generator/GeneratorObjectLiteralNode.java, pkl-core/src/main/java/org/pkl/core/ast/expression/generator/ObjectData.java, pkl-core/src/test/files/LanguageSnippetTests/input/generators/generatorNoMembers.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/generators/generatorNoMembers.err
If a generator object literal doesn't add any object members, we can simply use the parent in its place.
=> Add optimization for generator bodies that don't introduce new members

.circleci/config.pkl, .circleci/config.yml, .circleci/jobs/BuildNativeJob.pkl, .circleci/jobs/DeployJob.pkl, .circleci/jobs/GradleCheckJob.pkl, .circleci/jobs/GradleJob.pkl, .circleci/jobs/SimpleGradleJob.pkl
This should speed up our Mac release builds
=> Build with `m2pro.large` instances, not `macos.m1.large.gen1`

pkl-core/src/main/java/org/pkl/core/parser/Lexer.java, pkl-core/src/test/files/LanguageSnippetTests/input/basic/comments.pkl
Our old parser allowed block comment stacking, but it also allowed the user to not close the block comments properly:
```pkl
/* /* */ foo = 1
```
This can lead to a massive backtracking in the lexer, so we decided to remove this feature. Block comments don't stack anymore, so this previously valid Pkl code is not valid anymore:
```pkl
/* top /* nested */ top */ foo = 1
```
This is breaking change, but it's pretty easy to fix. Also our editor parsers (IntelliJ, tree-sitter, textMate) don't allow stacking.
Fixes #1014
=> Remove stacking of block comments

docs/modules/ROOT/pages/evolution-and-roadmap.adoc
I saw a typo and decided to open a quick PR to fix it. Please let me know of any guidelines I may have missed as I don't contribute to opensource projects often.
=> Fix typo in evolution-and-roadmap

pkl-cli/src/main/kotlin/org/pkl/cli/CliEvaluator.kt, pkl-cli/src/test/kotlin/org/pkl/cli/CliEvaluatorTest.kt
This PR fixes https://github.com/apple/pkl/issues/989
When specifying a directory instead of a file for the output, `pkl` won't crash anymore, but instead output an error message, suggesting `--multiple-file-output-path`.
=> Do not crash, but suggest '--multiple-file-output-path' when specifying a directory as output file

pkl-doc/src/main/kotlin/org/pkl/doc/PackageDataGenerator.kt
This fixes an issue that can possibly cause a StringIndexOutOfBoundsException when generating pkldoc.
The relative path should be based off the module name prefix, not the package name.
=> Fix incorrect substring

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/pklAllProjects.gradle.kts, buildSrc/src/main/kotlin/pklJavaLibrary.gradle.kts, buildSrc/src/main/kotlin/pklKotlinLibrary.gradle.kts
Previously, only sourceCompatibility and targetCompatibility were used, and they might cause issues like NoSuchMethodError when a newer javac compiles with -target older_release.
Note: it is good to use a new an up to date javac to avoid issues in the compiler itself, so having a proper `-release ..` configuration is vital.
See https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/
=> chore: use javac -release and kotlinc -Xjdk-release so the generated bytecode adheres to the APIs for the target Java release

pkl-core/src/main/java/org/pkl/core/ast/expression/unary/ImportGlobNode.java, pkl-core/src/main/java/org/pkl/core/module/ModuleKeyFactories.java, pkl-core/src/main/java/org/pkl/core/module/ModuleKeys.java, pkl-core/src/main/java/org/pkl/core/project/ProjectPackager.java, pkl-core/src/main/java/org/pkl/core/resource/ResourceReaders.java, pkl-core/src/main/java/org/pkl/core/util/GlobResolver.java, pkl-core/src/main/java/org/pkl/core/util/IoUtils.java, pkl-core/src/main/resources/org/pkl/core/errorMessages.properties, pkl-core/src/test/files/LanguageSnippetTests/input/errors/invalidFileUri1.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/errors/invalidFileUri2.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/errors/invalidFileUri3.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/errors/invalidFileUri4.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/errors/invalidFileUri1.err, pkl-core/src/test/files/LanguageSnippetTests/output/errors/invalidFileUri2.err, pkl-core/src/test/files/LanguageSnippetTests/output/errors/invalidFileUri3.err, pkl-core/src/test/files/LanguageSnippetTests/output/errors/invalidFileUri4.err
Opaque file URIs are URIs whose scheme-specific part does not start with `/`.
For example, `file:foo/bar.txt` is an opaque URI.
Currently, this has the unintentional behavior of: look for file `foo/bar.txt` from the process working directory.
These are effectively dynamics imports; from a single import, we can't statically analyze what it resolves as.
According to RFC-8089, File URIs must have paths that start with `/`. So, these are actually _not valid URIs_.
See the grammar defined in https://datatracker.ietf.org/doc/html/rfc8089#section-2
This changes Pkl's behavior so that these URIs are treated as errors.
=> Treat opaque file URIs as errors

docs/modules/java-binding/partials/cli-codegen-options.adoc, docs/modules/pkl-gradle/partials/gradle-codegen-properties.adoc, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/CliJavaCodeGeneratorOptions.kt, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/JavaCodeGenerator.kt, pkl-codegen-java/src/main/kotlin/org/pkl/codegen/java/Main.kt, pkl-codegen-java/src/test/kotlin/org/pkl/codegen/java/JavaCodeGeneratorTest.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/CliKotlinCodeGeneratorOptions.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/KotlinCodeGenerator.kt, pkl-codegen-kotlin/src/main/kotlin/org/pkl/codegen/kotlin/Main.kt, pkl-codegen-kotlin/src/test/kotlin/org/pkl/codegen/kotlin/KotlinCodeGeneratorTest.kt, pkl-gradle/src/main/java/org/pkl/gradle/PklPlugin.java, pkl-gradle/src/main/java/org/pkl/gradle/task/CodeGenTask.java, pkl-gradle/src/main/java/org/pkl/gradle/task/JavaCodeGenTask.java, pkl-gradle/src/main/java/org/pkl/gradle/task/KotlinCodeGenTask.java
This adds logic so that the Kotlin code generator also supports the "addGeneratedAnnotation" flag.
Also:
* Add Antora documentation
* Adjust names (generated-annotation -> add-generated-annotation)
* Adjust doc comments
=> Add Kotlin support for "addGeneratedAnnotation" flag

libpkl/src/main/c/pkl.c, libpkl/src/main/c/pkl.h, libpkl/src/main/java/org/pkl/libpkl/LibPkl.java, libpkl/src/nativeTest/kotlin/org/pkl/libpkl/LibPklJNA.kt, libpkl/src/nativeTest/kotlin/org/pkl/libpkl/LibPklTest.kt
This allows consumers of the native library to know which version of Pkl they're using, e.g. to build version-specific gates around newer functionality.
=> Expose version of Pkl within native library using `pkl_version`

docs/modules/bindings-specification/pages/message-passing-api.adoc
1. Change `Binary` to `Bytes` (new type representing binary data)
2. Add documentation for `http.rewrites` option
=> Improve message passing api docs

pkl-core/src/main/java/org/pkl/core/stdlib/base/ListingNodes.java, pkl-core/src/main/java/org/pkl/core/stdlib/base/MappingNodes.java, pkl-core/src/test/files/LanguageSnippetTests/input/listings/default.pkl, pkl-core/src/test/files/LanguageSnippetTests/input/mappings/default.pkl, pkl-core/src/test/files/LanguageSnippetTests/output/listings/default.pcf, pkl-core/src/test/files/LanguageSnippetTests/output/mappings/default.pcf, stdlib/base.pkl
This PR adds methods to `Listing` and `Mapping` that can be used to retrieve members. If the member for the index/key isn't present, it applies `default` to the index/key. In both cases, this is essentially sugar for `getOrNull(<index/key>) ?? default.apply(<index/key>)`.
I considered adding another method called something like `getOrElse` to these types (as well as `List` and `Map`). This two-argument method would work like `getOrNull` but in the event of no member being present would return the second argument.
I opted not to implement `getOrElse` since the null coalescing operator `??` already implements this in a more convenient way: `getOrNull(<index/key>) ?? <default value>`. I think the pattern of applying `default` should have its own method: for many users it's not always obvious …
=> Add `getOrDefault` method to `Listing` and `Mapping`

pkl-cli/src/test/kotlin/org/pkl/cli/CliEvaluatorTest.kt, pkl-cli/src/test/kotlin/org/pkl/cli/CliMainTest.kt, pkl-commons-cli/src/main/kotlin/org/pkl/commons/cli/commands/BaseOptions.kt
Fixes an issue where `http.noProxy` settings are ignored.
Closes #1142
=> Defer noproxy to settings.pkl or PklProject if not set explicitly

pkl-server/src/main/kotlin/org/pkl/server/Server.kt, pkl-server/src/main/kotlin/org/pkl/server/ServerMessagePackDecoder.kt, pkl-server/src/main/kotlin/org/pkl/server/ServerMessagePackEncoder.kt, pkl-server/src/main/kotlin/org/pkl/server/ServerMessages.kt, pkl-server/src/test/kotlin/org/pkl/server/AbstractServerTest.kt, pkl-server/src/test/kotlin/org/pkl/server/ServerMessagePackCodecTest.kt
This is a bugfix, where the `rewrites` option is currently ignored.
Also: return any illegal argument errors from creating the evaluator as an error in the CreateEvaluatorResponse
=> Fix: use http.rewrites to configure the evaluator in message passing API

buildSrc/src/main/kotlin/pklNativeExecutable.gradle.kts, docs/modules/release-notes/pages/0.29.adoc
Attempts to publish these artifacts is resulting in errors like "No Archiver found for the stream signature"
=> Disable publishing native executables to Maven Central

pkl-cli/src/main/kotlin/org/pkl/cli/repl/Repl.kt
The REPL now handles interrupts (Ctrl-C) in a more user-friendly way. Instead of exiting immediately, it behaves like other REPLs:
* If the line is non-empty or in a continuation, the buffer is cleared.
* If the line is empty, print a message with instructions on exiting the REPL.
* If another interrupt is sent immediately after, exit.
Pressing Ctrl-D immediately exits the REPL, as before.
=> Improve interrupt handling in `pkl repl`

pkl-commons-cli/src/main/kotlin/org/pkl/commons/cli/CliCommand.kt
In the original implementation the `org/pkl/commons/cli/PklCARoots.pem` resource is resolved relatively to the classloader associated with the class returned by `javaClass`. However, since this is an extension method for `HttpClient.Builder`, it means calling `javaClass` on the builder instance, which is actually defined in the system classpath.
Because of this, if the Pkl class is loaded by a different classloader compared to the one which contains JDK classes, which is totally possible in certain scenarios (e.g. with Gradle), then this resource resolution will fail.
The solution is to resolve `javaClass` against `this@CliCommand`, to use the classloader which loaded the jar with the `CliCommand` class to find the CA resource.
Closes https://github.com/apple/pkl/issues/1199
=> Fixed fallback certificates not working in certain classloader setups

pkl-cli/src/main/kotlin/org/pkl/cli/CliFormatterApply.kt, pkl-cli/src/main/kotlin/org/pkl/cli/CliFormatterCheck.kt, pkl-cli/src/main/kotlin/org/pkl/cli/CliFormatterCommand.kt, pkl-cli/src/main/kotlin/org/pkl/cli/commands/FormatterCommand.kt
This makes it easier to work with tools which return a list of file to format, e.g. to only handle files which have changed in a PR.
=> Allow formatting multiple files/directories

buildSrc/src/main/kotlin/BuildInfo.kt
Gradle does not support Java toolchains on Windows ARM right now. To enable running the project in this os/arch, we must omit multi-jdk test tasks.
See https://github.com/gradle/gradle/issues/29807
=> Disable multi-jdk testing when running on Windows ARM

pkl-doc/src/test/kotlin/org/pkl/doc/NativeExecutableTest.kt
Fixes a bug in the native tests for pkl-doc, which is causing them to fail.
=> Fix pkl-doc native test
